### PR TITLE
.Net: Fix CI pipeline for Windows runner

### PR DESCRIPTION
**Pull request by dmytrostruk**
### Motivation and Context

We have `windows` as OS in our CI matrix, but it is not used, and we build and run solution on Ubuntu only.
This PR enables Windows in pipeline.

Note: removal of `<returns></returns>` in changes was required to trigger .NET pipeline for testing.

Before:
image

After:
image

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by stephentoub** [comment]
What is the problem this is fixing? Thanks.

**Comment by dmytrostruk** [comment]
> What is the problem this is fixing? Thanks.

Sorry I didn't put PR description yet since I'm still working on it, and I need CI pipeline to run for testing. 

Problem: Even though we have `windows` as OS in our CI matrix, it is not used, and we build and run solution on Ubuntu only:
image

I want to enable running it on Windows as well.

**Comment by stephentoub** [comment]
Oh, wow, have we never been running on Windows, or is this a recent regression?

**Comment by dmytrostruk** [comment]
> Oh, wow, have we never been running on Windows, or is this a recent regression?

Not sure, but I'm just trying to fix it :) Should be ready soon.

**Comment by dmytrostruk** [comment]
> Should be ready soon.

Ready, it should work as expected now. I left screenshots in PR description.

**Review by westey-m — APPROVED** [review]

**Review by markwallace-microsoft — APPROVED** [review]

**Review by markwallace-microsoft — APPROVED** [review]

**Pull request merged**
