### PR TITLE
Python: Fixes for import_skill examples

### PR DESCRIPTION
**Pull request by Sailesh-2209**
### Motivation and Context

Fix for issue #1730 - Python: Core skills include incorrect syntax in usage documentation

### Description

Made changes to the examples in file_io_skill, math_skill, text_skill, time_skill, and wait_skill. Example for math_skill had the new keyword for object instantiation, which I removed too.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by Sailesh-2209** [comment]
> @Sailesh-2209 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by shawncal — CHANGES_REQUESTED** [review]
@Sailesh-2209 This PR contains several empty files, and some that appear unrelated to the name and description. Can you please revert/remove the extra files? Thanks for you contribution!

**Comment by HenriSchulte-MS** [comment]
I believe this should already have been fixed in #1731

**Comment by Sailesh-2209** [comment]
> @Sailesh-2209 This PR contains several empty files, and some that appear unrelated to the name and description. Can you please revert/remove the extra files? Thanks for you contribution!

Yup, sorry about that. This issue was fixed in #1731, so leaving this as is

**Comment by alexchaomander** [comment]
Closing since this has been resolved with #1731

**Pull request closed without merging**
