### PR TITLE
.Net: Ollama AI Connector

### PR DESCRIPTION
**Pull request by BLaZeKiLL**
### Motivation and Context
I am currently participating in [Microsoft AI Classroom Hackathon](https://microsoftaiclassroom.devpost.com/?ref_feature=challenge&ref_medium=discover) for which I am building an app using semantic kernel. Since I have a student account with Azure so don't have access to Azure Open AI services, but Ollama allows us to self host LLM models based on Llama2

1. Why is this change required?
  With this change semantic kernel can use Ollama as an AI connector.
2. What problem does it solve?
  Provides more options for AI services and allows integration with self hosted Ollama instances
3. What scenario does it contribute to?
  Plugin and memory plugins created by the community
4. If it fixes an open issue, please link to the issue here.
  N/A

### Description

I followed the implementation of the similar feature in python #3055 and HuggingFace Connector as it also operates over Http.
I have also added a PingOllamaAsync method which can be used to check if the specified model is available on the ollama instance pointed by ollama base url.

I was unable to execute all tests as I don't have access to OpenAI or Azure OpenAI.

I wasn't able to test the streaming implementation, not sure if it works. I would appreciate any feedback of the implementation as I am still new to semantic kernel.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by BLaZeKiLL** [comment]
> @BLaZeKiLL please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by markwallace-microsoft** [comment]
Thanks @BLaZeKiLL we'll take a look at this soon and provide feedback before we merge

**Comment by awaescher** [comment]
Looking forward to this!

Maybe you could simplify the code in `OllamaTextCompletion` with [OllamaSharp](https://github.com/awaescher/OllamaSharp)

```csharp
var uri = new Uri("http://localhost:11434");
var ollama = new OllamaApiClient(uri);
await ollama.StreamCompletion("How are you today?", "llama2", stream => Console.Write(stream.Response));
```

**Comment by BLaZeKiLL** [comment]
> Looking forward to this!
> 
> Maybe you could simplify the code in `OllamaTextCompletion` with [OllamaSharp](https://github.com/awaescher/OllamaSharp)
> 
> ```cs
> var uri = new Uri("http://localhost:11434");
> var ollama = new OllamaApiClient(uri);
> await ollama.StreamCompletion("How are you today?", "llama2", stream => Console.Write(stream.Response));
> ```

I'll take a look, If plugins are to be hosted separately it won't be an issue to add ollama sharp as a dependency

**Comment by BLaZeKiLL** [comment]
I have released a nuget with the above ollama connector as well as support for chat completion and embedding generation you can check it out here - https://www.nuget.org/packages/Codeblaze.SemanticKernel.Connectors.AI.Ollama

**Comment by BLaZeKiLL** [comment]
Looking forward to it

**Comment by markwallace-microsoft** [comment]
Ollama have announced OpenAI compatibility, see: https://ollama.ai/blog/openai-compatibility

So we may be able to use our existing OpenAI connector. @RogerBarreto can you investigate is this the case.

**Comment by RogerBarreto** [comment]
Closing this PR and assigning the original Author @BLaZeKiLL to the new one #4789 

Please ping me if you have any questions.

**Pull request closed without merging**
