### PR TITLE
Python: fix class type

### PR DESCRIPTION
**Pull request by yanzhang100**
### Motivation and Context

It should be "ChatMessageContent" type instead of "FunctionCallContent" type.

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by yanzhang100** [comment]
> @microsoft-github-policy-service agree [company="{your company}"]

@microsoft-github-policy-service agree company="Microsoft"

**Review by moonbox3 — APPROVED** [review]
Thanks for the fixes.

**Review by eavanvalkenburg — APPROVED** [review]

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/c748301a5dac1f6d4aad8850b5a1398f47ca27a9/README.md">Py3.10 Test Coverage</a><details><summary>Python 3.10 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>5690</b></td><td><b>902</b></td><td><b>84%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.10 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1287 | 1 :zzz: | 0 :x: | 0 :fire: | 15.106s :stopwatch: |

**Comment by moonbox3** [comment]
@yanzhang100 can you please fix the formatting (Ruff) error and push the code upstream? Thanks.

**Comment by yanzhang100** [comment]
> @yanzhang100 can you please fix the formatting (Ruff) error and push the code upstream? Thanks.
Fixed the formatting issue. But it shows another issue - Failed Python Test Coverage. Would you please suggest how to fix this? @moonbox3

**Pull request merged**
