### PR TITLE
.Net Ollama Connector [WIP]

### PR DESCRIPTION
**Pull request by RogerBarreto**
### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by Krzysztof318** [comment]
Nice to look at this code  😄

**Comment by BLaZeKiLL** [comment]
I'd be happy to contribute to this connector. Let me know if there is anything I can help with.

Currently, I don't see embedding support, I can take a look over that

**Comment by BLaZeKiLL** [comment]
https://ollama.ai/blog/openai-compatibility

Ollama just released OpenAI compatibility endpoints so it may be possible to use the existing OpenAI connector with Ollama

**Comment by Krzysztof318** [comment]
@BLaZeKiLL interesting, so example with LM-studio #4753 should also works with ollama

**Comment by RogerBarreto** [comment]
@BLaZeKiLL Thanks for being supportive and wishing to help on this feature. I made the latest changes to support the existing API and definitely would appreciate further changes to it to support embeddings, model change, and add the missing UnitTests to it. 

Most of the code is very close to the pattern @Krzysztof318 used in Gemini one, which is a good pattern. Suggest using/re-using some if his already made UT to cover the code in this PR if you can. 

I will need to work on other connectors for the next week, feel to jump in and push further changes from my latest commit moving forward. 

I will be happy to look into it.

**Comment by BLaZeKiLL** [comment]
I'd be happy to take this forward. I'll start with embedding support.

**Pull request merged**
