### PR TITLE
[Python Getting Started] Update `base_url` to `endpoint`

### PR DESCRIPTION
**Pull request by andrewDoing**
### Motivation and Context

1. This change helps users by being able to copy the Azure OpenAI endpoint directly
2. This solves the problem of getting a 404 Resource Not Found when using `base_url`
3. Getting Started in Python scenario

### Description

change `base_url` to `endpoint`

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/96b440f8c1b277ddcd15efd3ea4dcf9672101f2c/README.md">Py3.8 Test Coverage</a><details><summary>Python 3.8 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>5563</b></td><td><b>1020</b></td><td><b>82%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.8 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1207 | 11 :zzz: | 0 :x: | 0 :fire: | 19.504s :stopwatch: |

**Comment by prathyk** [comment]
I was very much excited to learn about semantic-kernel. I quickly jumped in to some tutorials and started trying it only to end up wasting 3 hours of my time debugging this issue. I hope this gets merged soon. Its not a good welcome for one who wants to learn semantic-kernel with Azure OpenAI account. 

Workaround that I'm using now: 
```python
chat = AzureChatCompletion(service_id=service_id, api_version=azure.api_version,
                           deployment_name="gpt-4", base_url=azure.api_base+"/openai", ad_token_provider=azure.token_provider)
```
Note how I'm appending *"/openai"* to base_url

**Review by eavanvalkenburg — APPROVED** [review]
Thanks

**Review by juliomenendez — APPROVED** [review]

**Comment by FlorianPydde** [comment]
Hi folks. It's still an issue today. I had to append the "/openai" to the base_url to make it work.  I am on sk 1.18.2.

**Comment by eavanvalkenburg** [comment]
hi, in this case you should use endpoint, and not base_url, base_url should contain the whole thing `openai/deployments/{deployment_name}` while endpoint will append that, see https://github.com/microsoft/semantic-kernel/blob/d06d230c292537ed5eb19a6f17532d455694a2da/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py#L82

**Comment by FlorianPydde** [comment]
Thanks for the quick answer. I tried with endpoint but I get a "resource not found" error.

**Comment by eavanvalkenburg** [comment]
can you share the broader code? and have you validated all the params?

**Comment by moonbox3** [comment]
> Thanks for the quick answer. I tried with endpoint but I get a "resource not found" error.

Please make sure your AZURE_OPENAI_API_VERSION is correct. If not, it will throw a 404. I just tested it right now and I see, via logging:

```
DEBUG:openai._base_client:HTTP Request: POST https://***.openai.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2024-09-01-preview "200 OK"
```

**Comment by FlorianPydde** [comment]
I have tested the openai sdk and sk and openai doesn't raise any error. 

```
client = AzureOpenAI(
    azure_endpoint=os.getenv("ENDPOINT"),
    api_key=os.getenv("API_KEY"),
    api_version="2024-05-01-preview",
)
completion = client.chat.completions.create(
    model=os.getenv("DEPLOYMENT_NAME"), messages=messages
)
```

```
chat_completion = AzureChatCompletion(
        deployment_name=os.getenv("DEPLOYMENT_NAME"),
        api_key=os.getenv("API_KEY"),
        api_version="2024-05-01-preview",
        endpoint=os.getenv("ENDPOINT"),
    )
```

**Comment by ahmedsza** [comment]
This  is so confusing.. I took the python quickstart and kept on getting the 404 error. I added the /openai to the base_url and all is good.. (thanks @FlorianPydde ) . Is this by design?
Should it be documented somewhere . or if the alternative is to set to the right api_version that should documented.

**Pull request merged**
