### PR TITLE
.Net: Update to Azure.AI.OpenAI version 1.0.0-beta.6

### LINKED ISSUE #2089: .NET: Package Azure.AI.OpenAI beta 6 release breaking change
**Describe the bug**
The latest Azure.AI.OpenAI beta 6 release has a breaking change, meaning having Azure.AI.OpenAI and SK as dependencies in the same project breaks at runtime.

**To Reproduce**
1. Create a new project with both Azure.AI.OpenAI (latest) and SK (latest) as dependencies
2. Create a chat completion using SK
3. See error

**Expected behavior**
No error.

**Screenshots**
None

**Platform**
 - OS: All
 - IDE: All
 - Language: C#
 - Source: SK version 0.17.230718.1-preview

**Additional context**
Updates to the latest package and fixes minor regression.

### PR DESCRIPTION
**Pull request by anthonypuppo**
### Motivation and Context
Utilize the latest version of the Azure.AI.OpenAI package. This provides support for the latest Azure OpenAI REST API versions (including function calling!) and fixes a minor regression.

Fixes #2089 

### Description

Update to Azure.AI.OpenAI version 1.0.0-beta.6 and fix minor regression.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#dev-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Review by shawncal — APPROVED** [review]

**Comment by shawncal** [comment]
Looks like we've got an integration test break with this update:
SemanticKernel.IntegrationTests.Planning.SequentialPlanner.SequentialPlannerTests.CreatePlanFunctionFlowAsync(useChatModel: True, prompt: "Write a joke and send it in an e-mail to Kai.", expectedFunction: "SendEmail", expectedSkill: "_GLOBAL_FUNCTIONS_")

       -------- Azure.RequestFailedException : 'System' is not one of ['system', 'assistant', 'user'] - 'messages.0.role'
       Status: 400 (model_error)

**Review by shawncal — CHANGES_REQUESTED** [review]
Integration tests failing. Updates needed in:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/AuthorRole.cs

**Comment by craigomatic** [comment]
Related to #1450

**Comment by anthonypuppo** [comment]
> Looks like we've got an integration test break with this update: SemanticKernel.IntegrationTests.Planning.SequentialPlanner.SequentialPlannerTests.CreatePlanFunctionFlowAsync(useChatModel: True, prompt: "Write a joke and send it in an e-mail to Kai.", expectedFunction: "SendEmail", expectedSkill: "_GLOBAL_FUNCTIONS_")
> 
> ```
>    -------- Azure.RequestFailedException : 'System' is not one of ['system', 'assistant', 'user'] - 'messages.0.role'
>    Status: 400 (model_error)
> ```
> 
> === SOLUTION =================================================================
> 
> @anthonypuppo Can you please update the strings ("System", "Assistant", "User") to lowercase in this file, and push an update to this PR? [dotnet\src\SemanticKernel.Abstractions\AI\ChatCompletion\AuthorRole.cs](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/AuthorRole.cs)

Done.

**Review by shawncal — APPROVED** [review]

**Pull request merged**
