### PR TITLE
.Net: Fix ignoring non-default search index name

### LINKED ISSUE #4213: MongoDB memory connector doesn't consume the index name parameter
**Describe the bug**

To performance vector search on MongoDB with the MongoDB connector, one has to create a vector search index:
1. https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-overview/
2. https://www.mongodb.com/docs/atlas/atlas-search/tutorial/create-index/

One can specify the index name for the search index. However, the MongoDB connector defaults to the index name "default" and there is no way to change it:

This class member is never used: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBMemoryStore.cs#L197

And when performing a nearest neighbor match, the index name is default to "default".

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

### PR DESCRIPTION
**Pull request by BorisDog**
Fixes #4213

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
@BorisDog can you fix the merge conflicts and we can get this merged

**Comment by BorisDog** [comment]
> @BorisDog can you fix the merge conflicts and we can get this merged
@markwallace-microsoft thanks, done.

**Review by markwallace-microsoft — APPROVED** [review]

**Comment by markwallace-microsoft** [comment]
@BorisDog one more merge conflict and also you need to run `dotnet format`

**Comment by BorisDog** [comment]
> @BorisDog one more merge conflict and also you need to run `dotnet format`

Done.

**Review by markwallace-microsoft — APPROVED** [review]

**Pull request merged**
