### PR TITLE
Python: Update .env with weaviate

### PR DESCRIPTION
**Pull request by zainhas**
Included weaviate env variables

### CODE REVIEW

**Comment by zainhas** [comment]
updated env variables users can add to use weaviate memory store

**Review by dmytrostruk — APPROVED** [review]

**Review by awharrison-28 — APPROVED** [review]

**Review by awharrison-28 — CHANGES_REQUESTED** [review]
There isn't any purpose for these env variables at the moment. To utilize them, could you add a method `def weaviate_settings_from_dot_env()` in the `python\semantic-kernel\utils\settings.py` file?

**Comment by zainhas** [comment]
Sure, will do.

**Comment by awharrison-28** [comment]
@zainhas I don't think this is necessarily blocking for this PR, but I think a previous PR to weaviate may have broken something related to accessing _additional_metadata in weaviate_memory_store.

**Review by awharrison-28 — APPROVED** [review]

**Comment by zainhas** [comment]
> 

@microsoft-github-policy-service agree

**Review by lemillermicrosoft — DISMISSED** [review]

**Review by lemillermicrosoft — APPROVED** [review]

**Review by awharrison-28 — APPROVED** [review]

**Comment by Jailson1318** [comment]
J6727038778

**Pull request merged**
