### PR TITLE
.Net: Add USearch Memory Connector

### PR DESCRIPTION
**Pull request by alexbarev**
### Motivation and Context

This PR aims to integrate a memory connector for `Cloud.Unum.USearch`.

### Description

The `Cloud.Unum.USearch` API presents certain limitations when interfacing with the IMemoryStore. This PR addresses these specific challenges:

1. **Lack of Collections**: `Cloud.Unum.USearch` stores only array embeddings without notion of collections and other string metadata. This PR adds a collection storage implementation using `ConcurrentDictionary` for metadata and `USearchIndex` for embeddings.

2. **Synchronous API**: The `Cloud.Unum.USearch` API is synchronous. To handle concurrent operations safely, lock storage has been implemented, providing a lock at the collection level for each operation.

3. **Key Mapping**: This PR also brings the mapping of `MemoryRecord` string keys to `ulong` types, ensuring compatibility with `USearch`. A `_nextFreeUSearchKey` variable has been added for easily obtaining a new key, but it comes with a limitation: the collection size remains unchanged even when records are deleted.

#### Future Considerations:

- **Persistence Mode**: While `USearch` supports persistence for embeddings, other `MemoryRecord` data should also be serialized and stored on disk. Currently, Parquet, Protobuf, or some C# native binary serialization methods are under consideration.

- **API Update**: Plans to add `ReadOnlySpan` \ `ReadOnlyMemory` into the API of `Cloud.Unum.USearch` and remove `float` to `ReadOnlyMemory<float>` castings in current PR.

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by ashvardanian** [comment]
Oh, amazing! @shawncal and @dluc, I am not 100% sure, but this might be the first embedded Vector Search engine in the .NET ecosystem. Please let us know if the ecosystem may benefit from our [other libraries](https://github.com/unum-cloud) 🤗

**Comment by alexbarev** [comment]
@microsoft-github-policy-service agree

**Comment by markwallace-microsoft** [comment]
@alexbarev We are working on an update memory connector strategy for Semantic Kernel. @dmytrostruk will publish an ADR with the new approach soon. Let's review this PR to see how it aligns with this strategy when the ADR is published.

**Comment by markwallace-microsoft** [comment]
Closing this and we can revisit as part of the updated memory connector plan

**Pull request closed without merging**
