### PR TITLE
Chat stream

### PR DESCRIPTION
**Pull request by dedalo**
### Motivation and Context

1. This change is required to add OpenAI chat stream capabilities to the Semantic Kernel, making it more versatile and useful in real-time chat applications.
2. The problem it solves is the inability to process and handle chat data in real-time, leading to a less interactive and responsive user experience.
3. This contributes to a scenario where developers can now integrate the Semantic Kernel with chat applications that require real-time processing and streaming of chat data.
4. This PR does not fix an open issue but improves the overall functionality and usability of the Semantic Kernel. might be duplicate of this https://github.com/microsoft/semantic-kernel/issues/378

### Description
  
This PR adds OpenAI chat stream capabilities to the Semantic Kernel. The changes include modifications to the existing code to enable handling of real-time chat data and sending partial responses to the client as the data is received. The overall approach focuses on maintaining the existing architecture while extending its functionality. This update enhances the Semantic Kernel's ability to work with chat applications requiring real-time interactions and responsiveness.

### Contribution Checklist

- [x ] The code builds clean without any errors or warnings
- [x ] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x ] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [x ] All unit tests pass, and I have added new tests where possible
- [x ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by dedalo** [comment]
@microsoft-github-policy-service agree

**Comment by dedalo** [comment]
@microsoft-github-policy-service agree

**Comment by shawncal** [comment]
Hi @dedalo, thank you for your contribution, and welcome to Semantic Kernel!

It would seem "great minds think alike," as we've got two very similar PRs at the moment: yours and this one:
https://github.com/microsoft/semantic-kernel/pull/829

It looks like #829 is the more comprehensive, as it includes updates to the samples and it uses the async streaming `IAsyncEnumerable<string>` pattern (instead of the Func callback) which is well-aligned with the Stream* methods in its sister classes, `AzuretTextCompletion` and `OpenAITextCompletion`.

That said, we'd love to include you as a contributor. Would you mind doing a review of https://github.com/microsoft/semantic-kernel/pull/829 and let us know if it'll work for you? If you believe it will, please go ahead and close this PR.

@RogerBarreto, please add the co-author tag to the PR description in #829:

Co-authored-by: dedalo <dedalo@gmail.com>

**Comment by dedalo** [comment]
reviewed https://github.com/microsoft/semantic-kernel/pull/829 and it works great for me, changing from on to the other was a brieze so I have my lab with signalr warking with RB implementation. waiting forward for the merge. closing this PR.

**Pull request closed without merging**
