### PR TITLE
Python: make input parameter optional

### PR DESCRIPTION
**Pull request by joowon-dm-snu**
### Motivation and Context

solve #2233 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by shawncal** [comment]
@mkarle Can you review please?

**Comment by joowon-dm-snu** [comment]
@shawncal  @mkarle 

This change will help `Planner` works better as `input` was always inserted into prompt because Planner get function parameters by `context.skills.get_functions_view()` I found this while porting stepwise planner into python

Here's sample example
image
image

If this PR is merged, 
image

**Review by mkarle — APPROVED** [review]

**Comment by mkarle** [comment]
I ran unit and integration tests as well as some samples and notebooks and didn't notice any regression.

**Comment by shawncal** [comment]
@joowon-dm-snu: Your branch is locked, so we cannot rebase and merge. The failing tests you're seeing above are not related to your change -- if you grant repo admins permissions to change your PR branch, we can update and merge the PR. Thanks!

**Comment by joowon-dm-snu** [comment]
@shawncal 
i made this PR in organization repo, `coxwave` and here is the [issue](https://github.com/orgs/community/discussions/5634)

The organization repo doesn't allow selecting the "Allow edits from maintainers" option. I've already made three PRs in that repo, so is it okay if I temporarily invite two people(@mkarle, @awharrison-28) to the repo? From now on, I'll probably proceed with my personal account.

**Comment by joowon-dm-snu** [comment]
> @shawncal i made this PR in organization repo, `coxwave/semantic-kernel` and here is the [issue](https://github.com/orgs/community/discussions/5634)
> 
> The organization repo doesn't allow selecting the "Allow edits from maintainers" option. I've already made three PRs in that repo, so is it okay if I temporarily invite two people(@mkarle, @awharrison-28) to the `coxwave/semantic-kernel`?
> 
> From now on, I'll probably proceed with my personal account.

@shawncal 
I transfer repo to private. problem solved! 
image

**Pull request merged**
