### PR TITLE
.Net: Python: Update multiple-results when streaming at a getting-started notebook.

### PR DESCRIPTION
**Pull request by jungwookim**
### Motivation and Context
Fix the multiple results when streaming.

### Description
Don't use enumerate and take a choice_index which is already provided in the result.

Expected)
Result 1: Blah Blah
Result 2: Blah Blah
Result 3: Blah Blah
Actual)
Result 1: BlahBlahBlah BlahBlahBlah
Result 2: 
Result 3: 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/a4e669e275446d6ec268c77a1a02a7050cc018be/README.md">Py3.10 Test Coverage</a><details><summary>Python 3.10 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>6532</b></td><td><b>756</b></td><td><b>88%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.10 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1526 | 1 :zzz: | 0 :x: | 0 :fire: | 24.093s :stopwatch: |

**Review by eavanvalkenburg — APPROVED** [review]

**Comment by eavanvalkenburg** [comment]
Good catch, thanks!

**Review by moonbox3 — APPROVED** [review]

**Comment by moonbox3** [comment]
Hi @jungwookim, thanks for this fix. Looks like there's a conflict in the notebook. Could you help resolve it please so we can merge this in?

**Comment by jungwookim** [comment]
Thanks for reviewing. Resolved conflicts and @microsoft-github-policy-service agree.

**Comment by jungwookim** [comment]
@microsoft-github-policy-service agree

**Review by moonbox3 — APPROVED** [review]

**Pull request merged**
