### PR TITLE
Copilot Chat: Url DataAnnotation is not compatible with Uri. Should be string

### PR DESCRIPTION
**Pull request by jpaarhuis**
Having Url annotation check with an Uri type always fails.

The reason is that the UrlAttribute IsValid method always checks if the value is of type string:
```cs
public override bool IsValid(object? value)
{
    if (value == null)
    {
        return true;
    }

    return value is string valueAsString &&
        (valueAsString.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
        || valueAsString.StartsWith("https://", StringComparison.OrdinalIgnoreCase)
        || valueAsString.StartsWith("ftp://", StringComparison.OrdinalIgnoreCase));
}
```

Changing Uri to string here works fine (tested) while keeping the annotation check.

For reference see: https://github.com/dotnet/runtime/issues/71008

### CODE REVIEW

**Comment by jpaarhuis** [comment]
@microsoft-github-policy-service agree

**Comment by gitri-ms** [comment]
FYI the markdown check failing is not due to this PR, it's a separate issue with a fix incoming

**Comment by jpaarhuis** [comment]
> FYI the markdown check failing is not due to this PR, it's a separate issue with a fix incoming

What about the merge gatekeeper? It's failing, but don't know why.

**Comment by gitri-ms** [comment]
> > FYI the markdown check failing is not due to this PR, it's a separate issue with a fix incoming
> 
> What about the merge gatekeeper? It's failing, but don't know why.

Merge gatekeeper is failing because the markdown check failed. Nothing to worry about there either.

**Review by gitri-ms — APPROVED** [review]

**Pull request merged**
