### PR TITLE
Python: Azure OpenAI returns empty delta at the end of the completion

### LINKED ISSUE #7114: Python: Bug: Azure OpenAI GPT-4o returns chuncks with empty delta at the end
**Impact**

Using streaming + tools with Azure OpenAI GPT-4O is crash for 50% of the calls.

**Describe the bug**

At the end of the streaming, the Azure OpenAI API with GPT-4o returns an empty delta object, which leads to expecting values on None objects.

**To Reproduce**

Returns an exception.

```python
# SDK setup
sk_base = Kernel()
chat_completion = AzureChatCompletion(service_id="default")
sk_base.add_service(chat_completion)

# Prompt and LLM settings
sk_settings = AzureChatPromptExecutionSettings(
    seed=42,
    temperature=0,
    tool_choice="auto",
    function_call_behavior=FunctionCallBehavior.EnableFunctions(
        auto_invoke=True,
        filters={},
    ),
)  # type: ignore

# History
history = ChatHistory()

# User message
history.add_user_message("Hi there")

stream = chat_completion.get_streaming_chat_message_contents(
    arguments=KernelArguments(),  # Required for auto invoking OpenAI tool calls
    chat_history=history,
    kernel=kernel,  # Required for OpenAI tool calls
    settings=sk_settings,
)
async for content in stream:
    res = content[0]
    if not res:
        continue
    yield str(content[0])
```

**Expected behavior**

Stream and returns chuncks.

**Platform**
 - OS: macOS
 - IDE: VS Code
 - Language: Python
 - Source: pip package v1.1.2

### PR DESCRIPTION
**Pull request by clemlesne**
### Context

Fix #7114.

### Contribution checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/README.md">Py3.10 Test Coverage</a><details><summary>Python 3.10 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/connectors/ai/open_ai/services</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py">azure_chat_completion.py</a></td><td>85</td><td>32</td><td>62%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py#L141">141</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py#L147-L148">147&ndash;148</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py#L157-L158">157&ndash;158</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py#L163-L180">163&ndash;180</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py#L184-L188">184&ndash;188</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py#L200-L211">200&ndash;211</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py">open_ai_chat_completion_base.py</a></td><td>168</td><td>70</td><td>58%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L100">100</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L104">104</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L124">124</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L149-L153">149&ndash;153</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L178">178</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L186">186</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L188">188</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L192">192</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L210-L215">210&ndash;215</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L233-L261">233&ndash;261</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L264-L275">264&ndash;275</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L290-L297">290&ndash;297</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L308-L316">308&ndash;316</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L332-L339">332&ndash;339</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L360">360</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L368">368</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L374-L377">374&ndash;377</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L389-L392">389&ndash;392</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/aacba78072b894fdf38bd8b5431f25aa8be0a4e1/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L423">423</a></td></tr><tr><td><b>TOTAL</b></td><td><b>6648</b></td><td><b>762</b></td><td><b>89%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python 3.10 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1575 | 1 :zzz: | 0 :x: | 0 :fire: | 19.616s :stopwatch: |

**Review by eavanvalkenburg — APPROVED** [review]
Thanks for fixing this!

**Review by moonbox3 — APPROVED** [review]

**Comment by moonbox3** [comment]
Hi @clemlesne, this change has caused many of the integration tests to fail. Can you have a look, please? https://github.com/microsoft/semantic-kernel/actions/runs/9840286760/job/27164184698#step:7:1501

**Comment by moonbox3** [comment]
Hi @clemlesne, I've reached out to a contact on the Azure OpenAI team to make sure this isn't a bug. Will let you know when I hear back (ETA early next week).

**Comment by yuichiromukaiyama** [comment]
Can this Pull Request be accepted if I resolve the conflicts...? 

If it can be accepted, I intend to resolve the conflicts myself.(However, I believe you've also contacted the Azure OpenAI team, so I plan to confirm before proceeding with the work.)

**Comment by moonbox3** [comment]
> Can this Pull Request be accepted if I resolve the conflicts...?
> 
> If it can be accepted, I intend to resolve the conflicts myself.(However, I believe you've also contacted the Azure OpenAI team, so I plan to confirm before proceeding with the work.)

Hi @yuichiromukaiyama, thank you for following up. I received the following response from a colleague:

"As far as I can tell, this is the intended behavior - you can see in AOAI public docs the example stream
[Azure OpenAI Service content filtering - Azure OpenAI | Microsoft Learn](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/content-filter?tabs=warning%2Cuser-prompt%2Cpython-new#sample-response-stream-passes-filters) does not have `delta` in the last event before [DONE]. I reproduced this myself calling the API directly as well. I think the nature of the async content filter is such that the content checking is done separately from the chat stream, so there is no `delta` associated with the async content filter results, rather it references a portion of the previous stream via
`content_filter_offsets`.
 
So, the chat completion would be streaming back with deltas, meanwhile content filter is asynchronously analyzing the stream, the content finishes first (last delta is {}), then the last content filter messages come through, then the stream finishes."

It does seem we would want the behavior in this PR.

**Comment by yuichiromukaiyama** [comment]
@moonbox3 Thank you! I have issued a pull request with resolved conflicts. I found some parts of the code that could be improved, so I rewrote them in a separate pull request.

https://github.com/microsoft/semantic-kernel/pull/8075

**Comment by moonbox3** [comment]
Superseded by #8075.

**Pull request closed without merging**
