### PR TITLE
Copilot Chat: Python: Azure Cognitive Search Connector

### PR DESCRIPTION
**Pull request by tawalke**
**Motivation and Context**
Why is this change required?
Enable Azure Cognitive Search Vector functionality to Semantic Kernel. 

**What problem does it solve?**
Allow Semantic Kernel to leverage the Azure Cognitive Search vector search preview as connector

**What scenario does it contribute to?**
Persistent Memory connectors

**Description**
Leverage the Azure Cognitive Search preview of vector search capabilities by using the Azure Python SDK. Adding completed connector for testing from initial PR to feature branch. 

### Contribution Checklist

- [X] The code builds clean without any errors or warnings
- [X] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [ ] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [x] All unit tests pass, and I have added new tests where possible
- [X] I didn't break anyone :smile:

### CODE REVIEW

**Comment by tawalke** [comment]
Hi @mattmsft Please review and test connector from this branch/PR.

**Comment by tawalke** [comment]
@mattmsft per our chat.

**Comment by tawalke** [comment]
@mattmsft Per our discussion, I have updated the formatting for integration tests that was causing the One test failure, changed the create index to do both update and create. Please review. 

@alexchaomander This PR is ready for review and ACS team testing with samples.

**Comment by mattmsft** [comment]
> @mattmsft Per our discussion, I have updated the formatting for integration tests that was causing the One test failure, changed the create index to do both update and create. Please review.
> 
> @alexchaomander This PR is ready for review and ACS team testing with samples. All tests are passing within this PR.

Thanks. Currently testing

**Comment by mattmsft** [comment]
I can't use the following code using this connector:

```
# Add some documents to the semantic memory
await kernel.memory.save_information_async(
    "aboutme", id="info1", text="My name is Andrea"
)
```

Fails with the following error:
```
ResourceNotFoundError: () No index with the name 'aboutme' was found in the service 'my-service-name'.
```

Wondering if we should catch this exception and create the index opportunistically in this case. This will make the search connector behave like the other connectors as well.

**Comment by tawalke** [comment]
Hi @mattmsft I've updated the memory_store per our discussion in preparation for the release of updated Azure SDK package. I've changed status of PR so that it is ready for review by team as well. Please review and advise, if there are additional items prior to our sync.

**Comment by tawalke** [comment]
@mattmsft Per our discussion, updated toml to dev feed, added vector search and CORS into Search Index creation. Please review.

**Comment by tawalke** [comment]
Hi @mattmsft Per our conversation: Reviewed merge, set dev feed back to desired version.

**Comment by tawalke** [comment]
@mattmsft Per feedback: Timestamp (datetime) updated for memory record conversion ready for your review.

**Comment by tawalke** [comment]
Closing per other PR being completed for ACS connector.

**Pull request closed without merging**
