### PR TITLE
Add Lint Workflow

### PR DESCRIPTION
**Pull request by AdityaGudimella**
### Motivation and Context
This PR adds a Lint Github workflow so that code style rules can be enforced for PRs.

1. This forms a baseline workflow that can be used as a template for future workflows that will be added.
2. It helps enforce code style rules. Currently it only checks PyCodeStyle and PyFlakes. Others will be added in the future.
3. Contributes to automated testing
4. Does not fix any open issue.

### Description
Added Ruff as a dev dependency. Added Github workflow which runs Ruff.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Review by dluc — DISMISSED** [review]

**Comment by dluc** [comment]
@jjhenkel I'm all for merging this, could you test and approve?

> Are there designated folks from the main SK team that are going to sign off, or are those of us working on SK Python going to be the ones to approve? Could do both? Thoughts?

no one designated, but having your approvals would be a great plus at least as a sign that everything is in order. While we're in preview we can move fast. We love small PRs, please help with that :-) I'll help with design and sync across languages.

**Comment by AdityaGudimella** [comment]
@jjhenkel There are a couple of ways to do what you want. Please tell me which one you prefer.
1. Use a separate tool to run tests locally.
2. Use a single tool (like [nox](https://nox.thea.codes/en/stable/)) that can be used locally and will also be used in the github actions.
3. Make a simple cli that runs the different tests and use it both locally and in the workflow.

I personally prefer Option 2 because it keeps things consistent between the workflows and local development. Also what is `act`? Could you provide a link to it please?

**Comment by jjhenkel** [comment]
@AdityaGudimella when I refer to testing here I just mean testing the workflow yml you wrote (not tests for the code). I was using this tool: https://github.com/nektos/act to verify things locally (and, to get things to run, I needed to make those small changes)

**Review by jjhenkel — CHANGES_REQUESTED** [review]

**Review by dluc — APPROVED** [review]

**Review by pixelbits-mk — APPROVED** [review]
## ✅ APPROVED - AI Code Review

### 📋 Summary
Simple change detected - This PR is a straightforward addition of linting configuration and CI workflow. The changes are infrastructure/tooling focused: adding Ruff linter as a dev dependency, configuring a GitHub Actions workflow for linting, and making a minor formatting fix. No architectural, security, performance, or complex development patterns are involved. The changes are well-structured and follow good DevOps practices. Inspirational review included to acknowledge the valuable contribution toward code quality automation.

🌟 **Your thoughtful implementation of parallel lint jobs for both Ruff and Black shows excellent attention to CI/CD scalability, setting up a robust foundation that will help the entire team maintain high code quality standards.**

---
*🤖 Generated by AI Code Review Agent*

**Pull request merged**
