### PR TITLE
.Net: Converted examples 52 and others to tests

### PR DESCRIPTION
**Pull request by Krzysztof318**
### Motivation and Context

PR #4526 

### Description

Converted examples 52 and 75 to tests
Fix samples project files formatting based on common solution resharper settings.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
@Krzysztof318 can you simplify this PR to remove all of the formatting changes?

**Comment by Krzysztof318** [comment]
@markwallace-microsoft Hi, I can. Just need drop one commit.
But by the way, I would like to know why there are such restrictive resharper settings in the repo if they are not respected in many files anyway?

**Comment by dmytrostruk** [comment]
> I would like to know why there are such restrictive resharper settings in the repo if they are not respected in many files anyway?

I think resharper settings are obsolete now. We use `dotnet format` to format the code. If you run `dotnet build` with `Release` configuration, `dotnet format` will be triggered automatically for you.

**Comment by Krzysztof318** [comment]
@markwallace-microsoft formatting commit dropped

**Comment by Krzysztof318** [comment]
@dmytrostruk I understand but it would be good to adjust the resharper settings file to be equal with .editorconfig or remove it, it causes a lot of red flags in the project

**Review by markwallace-microsoft — APPROVED** [review]

**Review by markwallace-microsoft — APPROVED** [review]
Just need to run dotnet format

**Comment by Krzysztof318** [comment]
Fixed other samples. Btw. Example74_FlowOrchestrator is not convertible to tests due to used Console.ReadLine

**Review by RogerBarreto — APPROVED** [review]

**Review by markwallace-microsoft — APPROVED** [review]

**Pull request merged**
