### PR TITLE
Python: fixes for base class issues

### PR DESCRIPTION
**Pull request by eavanvalkenburg**
### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by moonbox3** [comment]
This all seems good to me.

**Review by moonbox3 — APPROVED** [review]

**Comment by moonbox3** [comment]
@eavanvalkenburg I've been trying to look into the Python 3.9 errors. Could there be something with the specific pydantic version being used in Py 3.9? There could be some small difference in how pydantic is handling the validation for constrained strings.

**Comment by eavanvalkenburg** [comment]
@moonbox3 found it, passes tests now, turns out there was something in the ChatResponse object that was causing this for py3.9 (a | in there somewhere, which is not supported in py3.9, only 3.10+).

**Review by alexchaomander — APPROVED** [review]
LGTM!

**Pull request merged**
