### PR TITLE
Python: Potential feature : support sequence of values in MathSkill

### LINKED ISSUE #3024: Python: ActionPlanner create_plan_async error
**Describe the bug**
JSONDecodeError when executing 'plan = await planner.create_plan_async(goal=question)'.

**To Reproduce**
import semantic_kernel as sk
from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion, OpenAITextEmbedding
from semantic_kernel.connectors.ai.open_ai import AzureChatCompletion, AzureTextEmbedding

kernel = sk.Kernel()

userAzureOpenAI = True

if userAzureOpenAI:
    deployment, api_key, endpoint = sk.azure_openai_settings_from_dot_env() 
    kernel.add_text_completion_service("azureopenaicompletion", AzureChatCompletion(deployment, endpoint, api_key))
    kernel.add_text_embedding_generation_service("azureopenaiembedding", AzureTextEmbedding("text-embedding-ada-002", endpoint, api_key))
else:
    api_key, org_id = sk.openai_settings_from_dot_env()
    kernel.add_text_completion_service("openaicompletion", OpenAIChatCompletion("gpt-3.5-turbo-0301", api_key, org_id))
    kernel.add_text_embedding_generation_service("openaiembedding", OpenAITextEmbedding("text-embedding-ada-002", api_key, org_id))

from semantic_kernel.planning import ActionPlanner

planner = ActionPlanner(kernel)

from semantic_kernel.core_skills import MathSkill
kernel.import_skill(MathSkill(), "math")
print("Adding the tools for the kernel to do math ...")
print("\n*** Lets do some math!! ***")

question = "What is the sum of all the integers from 100 to 1?"

print(f"🧲 Finding the most similar function available to get that done...")
plan = await planner.create_plan_async(goal=question)

**Expected behavior**
Find the 'math.Add' function to use.

**Screenshots**
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File [~/Work/.venv/lib/python3.11/site-packages/semantic_kernel/planning/action_planner/action_planner.py:115](https://file+.vscode-resource.vscode-cdn.net/.../~/Work/.venv/lib/python3.11/site-packages/semantic_kernel/planning/action_planner/action_planner.py:115), in ActionPlanner.create_plan_async(self, goal)
    114 try:
--> 115     generated_plan = json.loads(generated_plan_str)
    116 except json.decoder.JSONDecodeError as e:

File [/opt/homebrew/Cellar/python](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python)@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File [/opt/homebrew/Cellar/python](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python)@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File [/opt/homebrew/Cellar/python](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python)@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:353, in JSONDecoder.raw_decode(self, s, idx)
    352 try:
--> 353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:

JSONDecodeError: Expecting ',' delimiter: line 5 column 11 (char 136)

During handling of the above exception, another exception occurred:

PlanningException                         Traceback (most recent call last)
[....ipynb](https://file+.vscode-resource.vscode-cdn.net/....ipynb) Cell 9 line 3
     [30](vscode-notebook-cell:/....ipynb#X16sZmlsZQ%3D%3D?line=29) #question = "What is the sum of 100 and 1?"
     [32](vscode-notebook-cell:/....ipynb#X16sZmlsZQ%3D%3D?line=31) print(f"🧲 Finding the most similar function available to get that done...")
---> [33](vscode-notebook-cell:....ipynb#X16sZmlsZQ%3D%3D?line=32) plan = await planner.create_plan_async(goal=question)

File [~/Work/.venv/lib/python3.11/site-packages/semantic_kernel/planning/action_planner/action_planner.py:119](https://file+.vscode-resource.vscode-cdn.net/.../~/Work/.venv/lib/python3.11/site-packages/semantic_kernel/planning/action_planner/action_planner.py:119), in ActionPlanner.create_plan_async(self, goal)
    117     self._logger.error("Encountered an error while parsing Plan JSON.")
    118     self._logger.error(e)
--> 119     raise PlanningException(
    120         PlanningException.ErrorCodes.InvalidPlan,
    121         "Encountered an error while parsing Plan JSON.",
    122     )
    124 self._logger.info(
    125     f"Python dictionary of plan generated by ActionPlanner:\n{generated_plan}"
    126 )
    128 if not generated_plan["plan"]:

PlanningException: (<ErrorCodes.InvalidPlan: 1>, 'Encountered an error while parsing Plan JSON.', None)

**Platform**
 - OS: MacBook M2 Pro
 - IDE: VS Code
 - Language: Python 3.11.5
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**
No error when the following 'question' is provided: question = "What is the sum of 100 and 1?"

### PR DESCRIPTION
**Pull request by AdarshAcharya5**
### Motivation and Context
This is a small patch for issue #3024 rather than a full fix. Currently, MathSkill only supports addition and subtraction of two single numeric values. This could be scaled to support these operations on a given sequence of values.

### Description
Fixes #3024
Output for code in #3024 : 

Screenshot (486)

### Contribution Checklist
- [X] The code builds clean without any errors or warnings
- [X] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [X] I didn't break anyone :smile:

### CODE REVIEW

**Comment by AdarshAcharya5** [comment]
@awharrison-28 If this is an intended feature, let me know and I can write tests to support this, else we can close this PR.

**Review by markwallace-microsoft — APPROVED** [review]

**Comment by AdarshAcharya5** [comment]
@dmytrostruk Sure!.

**Comment by AdarshAcharya5** [comment]
@dmytrostruk . The unit tests should run now. I'm not sure if adding additional tests for this particular change would be feasible as it uses the completion from gpt to replace the textual values with the actual sum of all the values.  Although maybe we can integrate sequence processing as a feature within math_skill itself. If that's an intended feature, let me know!. I'd love to contribute!.

**Comment by dmytrostruk** [comment]
> The unit tests should pass now.

@AdarshAcharya5 It looks like this test is still failing - `tests/unit/planning/test_plan_execution.py::test_invoke_multi_step_plan_async_with_variables`. 

I would probably leave `MathSkill.add` method as it is at the moment. It's responsible for adding two values and I'm not sure we need to extend its functionality, at least for now.
In case if we want to support operations for sequence of values, we can add separate methods for that, like `sum` for example.

But again, `MathSkill` is presented mostly for demonstration purposes to show what is possible. We expect users to create their own skills/plugins to cover their concrete scenarios. 

If you don't mind, I will close this PR for now. Feel free to re-open it or create a new one if you will see potential use cases for `MathSkill` extension. Thanks a lot!

**Comment by AdarshAcharya5** [comment]
@dmytrostruk Understood!. I do agree that it might probably be better to just let it be. There's no need to overcomplicate the examples.

**Pull request closed without merging**
