### PR TITLE
Python: Microsoft Guidance Integration

### PR DESCRIPTION
**Pull request by JTremb**
### Motivation and Context
The idea behind this PR is to integrate Guidance (https://github.com/microsoft/guidance) into SemanticKernel

Currently creating a draft PR to gather feedbacks on the integration. The format would be a bit different to enable both SK skills and Guidance format in the same template (see below).

### Description

My goal was to enable both SK and guidance format into the same prompt to leverage the strength of the two formats/features.
Guidance handlebars format would enhance the base SK format.

First , guidance was added as a new connector with a separate PromptTemplateEngine.
Example of kernel initialization -> 

```python
import semantic_kernel as sk
import semantic_kernel.connectors.ai.guidance as sk_guidance

kernel = sk.Kernel(prompt_template_engine=GuidanceTemplateEngine())

kernel.add_text_completion_service(
        service_id="guidance-service",
        service=sk_guidance.GuidanceAOAITextCompletion(
            model_id="text-davinci-003",
            deployment_name="[Name]",
            endpoint="[Endpoint]",
            api_key="[Key]",
        ),
    )

```
 
The kernel needs to be created with `prompt_template_engine=GuidanceTemplateEngine()` to support Handlebars format.

The template format is essentially the same *except* for variable rendering.  To pass the variable rendering to guidance, variables need to be preceded with a percent (%) sign (maybe another char would be better ?). Otherwise the rendering of the variable can be done by SK.  A special char is needed so SK template engine does not evaluate the expression as a function and fails because it doesn't exist.

E.g :
```
my {{%book}}
```
The `book` variable rendering will be done by guidance. GuidanceTemplateEngine will remove the percent sign and pass `my {{book}}` to guidance.

```
my {{$book}}
```
The variable will be rendered by SK template engine first and the rendered value will be passed to guidance.

Full prompt example ->
```python
 sk_prompt = """The following is a character profile for an RPG game in JSON format.
{
    "description": "{{%description}}",
    "name": "{{gen 'name'}}",
    "age": {{gen 'age' stop=','}},
    "armor": "{{#select 'armor'}}leather{{or}}chainmail{{or}}plate{{/select}}",
    "weapon": "{{select 'weapon' options=valid_weapons}}",
    "class": "{{gen 'class'}}",
    "biography": "{{gen 'biography'}}",
    "mantra": "{{gen 'mantra'}}",
    "strength": {{gen 'strength' stop=','}},
    "items": [{{#geneach 'items' num_iterations=3}}
        "{{gen 'this'}}",{{/geneach}}
    ]
}"""
valid_weapons = ["sword", "axe", "mace", "spear", "bow", "crossbow"]

context = kernel.create_new_context()
sk_function = kernel.create_semantic_function(sk_prompt)
context.variables.set("description", "A quick and nimble fighter.")
context.variables.set("valid_weapons", valid_weapons)
output = sk_function.invoke(context=context)
```

Output =>

```json
{
    "description": "A quick and nimble fighter.",
    "name": "Fighter",
    "age":  25,
    "armor": "leather",
    "weapon": "sword",
    "class": "warrior",
    "biography": "The Fighter is a brave and courageous warrior who has been trained in the art of combat since a young age. He is a master of swordsmanship and is always ready for a fight.",
    "mantra": "I will fight for what is right!",
    "strength":  10,
    "items": [
        "sword",
        "shield",
        "potion",
    ]
}
```

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by alexchaomander** [comment]
@slundberg @marcotcr would love if you two could take a look and give @JTremb some feedback!

**Comment by matthewbolanos** [comment]
One of the nice things about Guidance is its ability to return multiple outputs for a single program. Right now, the `TextCompletionClientBase` class's `complete_async` only allows returning a single text value. Would it make sense to update Semantic Kernel so that a dictionary can be returned back?

**Review by markwallace-microsoft — COMMENTED** [review]
@JTremb thanks for creating this PR. Guidance is a great project and we're very happy to see this integration with the Semantic Kernel.

One of our top priorities is reaching a 1.0 release of the Semantic Kernel core with a consistent feature set across .Net, Python and Java. For .Net we are extracting the default template engine into it's own package so it will become a Semantic Kernel extension. Likewise other template engines could also be developed as optional extensions.

Can we make the Guidance prompt template engine into a seperate Python library that developers can use together with the Semantic Kernel? That way we can measure it's usage and use this as a signal to develop a strategy to support .Net and Java?

**Comment by JTremb** [comment]
> Can we make the Guidance prompt template engine into a seperate Python library that developers can use together with the Semantic Kernel? That way we can measure it's usage and use this as a signal to develop a strategy to support .Net and Java?

@markwallace-microsoft  Absolutely,  I can make this PR a separate project. Would you suggest having one project for the Guidance integration or a more generic "experimental python extension" project that could contains different extensions ?

**Comment by lemillermicrosoft** [comment]
Thanks for your PR and contribution. For now, we are closing old drafts. Please re-open as appropriate.

**Comment by smpurkis** [comment]
So did this go in or not?

**Pull request closed without merging**
