### PR TITLE
Python: Support for cases where "logprobs" does not exist

### PR DESCRIPTION
**Pull request by yuichiromukaiyama**
### Motivation and Context

1. Why is this change required?
An error has occurred.
https://github.com/microsoft/semantic-kernel/issues/4923

2. What problem does it solve?
Non-existent property lobprobs is referenced when using Azure OpenAI Chat Completion.

[Swagger 2023-12-01-preview](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-12-01-preview)
[Swagger 2023-05-15](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2023-05-15/inference.json)

3. What scenario does it contribute to?
When using Azure OpenAI ChatCompletion

4. If it fixes an open issue, please link to the issue here.
https://github.com/microsoft/semantic-kernel/issues/4923

### Description

Azure OpenAI ChatCompletion does not return logprobs.
Thus, the following code would be "AttributeError: 'Choice' object has no attribute 'logprobs'".

```python
    def _get_metadata_from_chat_choice(self, choice: Union[Choice, ChunkChoice]) -> Dict[str, Any]:
        """Get metadata from a chat choice."""
        return {
            "logprobs": choice.logprobs,
        }
```

do the following

```python
def _get_metadata_from_chat_choice(self, choice: Union[Choice, ChunkChoice]) -> Dict[str, Any]:
    """Get metadata from a chat choice."""
    return {
        "logprobs": getattr(choice, "logprobs", None),
    }
```

### Contribution Checklist

- [- ] The code builds clean without any errors or warnings
- [- ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [-] All unit tests pass, and I have added new tests where possible
- [- ] I didn't break anyone :smile:

### CODE REVIEW

**Review by moonbox3 — APPROVED** [review]
Hi @yuichiromukaiyama, thank you for your work on this. I agree that it seems like useful to have this type of error handling as it appears the logprobs attribute may not always be present (depending upon what underlying model you're using). I see on the following [page](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions) that it mentions that `logprobs` is not available with `gpt-35-turbo`. Otherwise, in the swagger spec links you provided, for both 2023-05-15-previous and 2023-12-01-preview, they both contain the `logprobs` properties.

**Comment by moonbox3** [comment]
@yuichiromukaiyama note that our GitHub actions `markdown-link-check` step is currently failing -- it isn't related to your changes. We're trying to investigate as it is blocking our pipelines.

**Review by eavanvalkenburg — APPROVED** [review]
Thanks for adding this @yuichiromukaiyama

**Comment by yuichiromukaiyama** [comment]
Thank you so much！

**Comment by moonbox3** [comment]
@yuichiromukaiyama your change went in just in time for the latest [release](https://github.com/microsoft/semantic-kernel/releases/tag/python-0.5.1.dev). Thank you for your contribution!

**Comment by veeruhai** [comment]
I am still getting error..I am using "0.5.1.dev0", I see latest code ,but not sure issues is resolved completely 

def _get_metadata_from_chat_choice(self, choice: Union[Choice, ChunkChoice]) -> Dict[str, Any]:
    """Get metadata from a chat choice."""
    return {
        "logprobs": getattr(choice, "logprobs", None),
    }

image

**Comment by yuichiromukaiyama** [comment]
@veeruhai 
Do you fall under this problem? I think there are cases where logprobs do not exist for APIs other than ChatCompletion.

https://github.com/microsoft/semantic-kernel/discussions/5011

**Comment by veeruhai** [comment]
@yuichiromukaiyama , 
for me none of python notebooks working, I am using AzureOpenAI service, followed your workaround and changed PromptTemplate to  ChatPromptTemplate in kernel  .now I am able to run 00-getting-started notebook and basic planner notebook. Still facing same error for other planner type. 

image

**Comment by yuichiromukaiyama** [comment]
@veeruhai 

I investigated the issue and I believe it is the same as the one I described in the "Discussion".

Both use PromptTemplate, and the error seems to be occurring in a class that I have not modified.

The problem can be solved by changing the PromptTemplate used in this class to ChatPromptTemplate.

https://github.com/yuichiromukaiyama/semantic-kernel/blob/9cedc95b4ce9bf7aff6ae16892df757076ca1bbb/python/semantic_kernel/planning/sequential_planner/sequential_planner.py#L62

I believe that the sequential planner also performs the following process:

https://github.com/yuichiromukaiyama/semantic-kernel/blob/9cedc95b4ce9bf7aff6ae16892df757076ca1bbb/python/semantic_kernel/kernel.py#L171-L172

To solve the root cause, I plan to issue a PR to make the following changes:

↓

In the following section, kernel.register_semantic_function is called in _init_flow_function of SequentialPlanner.

https://github.com/yuichiromukaiyama/semantic-kernel/blob/9cedc95b4ce9bf7aff6ae16892df757076ca1bbb/python/semantic_kernel/planning/sequential_planner/sequential_planner.py#L74-L75

Since the use of PromptTemplate is enforced in Planner, TextCompletionClientBase is used in the following section:

https://github.com/yuichiromukaiyama/semantic-kernel/blob/9cedc95b4ce9bf7aff6ae16892df757076ca1bbb/python/semantic_kernel/kernel.py#L754

There is TextCompletionClientBase, which is inherited by OpenAITextCompletionBase.

https://github.com/yuichiromukaiyama/semantic-kernel/blob/9cedc95b4ce9bf7aff6ae16892df757076ca1bbb/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_completion_base.py#L29-L30

OpenAITextCompletionBase also has the corresponding logprobs code.

https://github.com/yuichiromukaiyama/semantic-kernel/blob/9cedc95b4ce9bf7aff6ae16892df757076ca1bbb/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_completion_base.py#L144

This will be rewritten as optional in the same way.

**Comment by ymuichiro** [comment]
@veeruhai I have issued a pull request.
https://github.com/microsoft/semantic-kernel/pull/5071

**Pull request merged**
