### PR TITLE
.Net: Update M.E.AI.Abstractions version

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
Bumped the version of Microsoft.OpenApi.ApiManifest being included to pull in https://github.com/microsoft/OpenApi.ApiManifest/pull/117, which was breaking the build.

**Comment by stephentoub** [comment]
Ugh, now it's blocked on Microsoft.Plugins.Manifest having a similar upper bound set. Looks like a fix was made to that repo but there's no nuget package with that fix yet.

**Comment by stephentoub** [comment]
@RogerBarreto, do you know what's wrong with CI here?

**Comment by RogerBarreto** [comment]
@stephentoub AFAIK 2 UT failing only.

**Review by RogerBarreto — APPROVED** [review]

**Comment by stephentoub** [comment]
Yeah, I just couldn't figure out which. But whatever it was, it seems to have resolved itself.

**Pull request merged**
