### PR TITLE
Python: .Net: Fixed typos based on new spell checker vocabulary

### PR DESCRIPTION
**Pull request by dmytrostruk**

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/eaad69c8a26dc592884f41b82b6e7b23e33de7c9/README.md">Py3.8 Test Coverage</a><details><summary>Python 3.8 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>5545</b></td><td><b>1020</b></td><td><b>82%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.8 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1206 | 11 :zzz: | 0 :x: | 0 :fire: | 24.268s :stopwatch: |

**Review by alliscode — APPROVED** [review]

**Comment by MediVik333** [comment]
Aprove

**Review by crickman — APPROVED** [review]

**Comment by dmytrostruk** [comment]
@dsgrieve @johnoliver Please review this PR. It looks like there are build failures in Java pipelines as well. Please let me know if it's possible to resolve them. Thank you!

**Comment by MediVik333** [comment]
> @dsgrieve @johnoliver Please review this PR. It looks like there are build failures in Java pipelines as well. Please let me know if it's possible to resolve them. Thank you!

I really don't understand how to resolve this, im very sorry, mabe you have definition how complet it more easy?

**Review by markwallace-microsoft — APPROVED** [review]

**Pull request merged**
