### PR TITLE
Python: linter fix

### PR DESCRIPTION
**Pull request by joowon-dm-snu**
### Motivation and Context

lint fix for pre commit checks

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Review by awharrison-28 — DISMISSED** [review]

**Comment by joowon-dm-snu** [comment]
black failed -> re-lint. maybe pre-commit need change?
image

**Comment by awharrison-28** [comment]
@joowon-dm-snu try running `poetry run black .` standalone. I'm not sure why it's getting missed by the lumped command, but I think this will get this PR through.

**Comment by joowon-dm-snu** [comment]
running `poetry run pre-commit run -c .conf/.pre-commit-config.yaml -a` adds line 116
But `poetry run black .` doesn't like that change
```
    async def run_async(
            self,
            *functions: Any,
            input_context: Optional[SKContext] = None,
            input_vars: Optional[ContextVariables] = None,
            input_str: Optional[str] = None,
    ) -> SKContext:
            <----------- new line added
        # if the user passed in a context, prioritize it, but merge with any other inputs
        if input_context is not None:
```
image

**Comment by joowon-dm-snu** [comment]
@awharrison-28 I found the issue, black version difference was the problem.
pre-commit uses black ver 22.3.0 but lint checker might using 23.1

**Review by awharrison-28 — APPROVED** [review]

**Pull request merged**
