### PR TITLE
Python: Adding Python SQLite connector 

### PR DESCRIPTION
**Pull request by 1yefuwang1**
### Motivation and Context

1. Why is this change required? : Please see https://github.com/microsoft/semantic-kernel/issues/1998
2. What problem does it solve?  Bing feature parity to Python implementation
3. What scenario does it contribute to? Allow Python users leverage SQLite as memory storage
### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by 1yefuwang1** [comment]
The ruff lint task failed due to some strange EACCESS error 
image
https://github.com/microsoft/semantic-kernel/actions/runs/5768846010/job/15640279770?pr=2332

I don't have enough access to retry. Can anyone have a look?

**Comment by awharrison-28** [comment]
Hi @1yefuwang1 - embedded chroma (default for chroma_memory_store) already uses sqlite as it's backing storage, so this a little redundant to have in the main repo. 

Please see https://github.com/microsoft/semantic-kernel/pull/2503 - we are updating our contribution guidelines regarding plugins and connectors. This is a good candidate for a connector published separately from SK - we'll have further guidance on how/where to do so soon.

**Comment by 1yefuwang1** [comment]
Hi, @awharrison-28 thank you for the notice. I'll follow new guideline when it's ready.
Chromadb does leverage sqlite3 as its internal storage engine. However, IMHO it's an implementation detail. So, I wouldn't consider sqlite3 connector as redundant. There's still an [SQLite Connector in C#](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteMemoryStore.cs).

**Comment by lemillermicrosoft** [comment]
Thanks for your PR and contribution. For now, we are closing old drafts. Please re-open as appropriate.

**Pull request closed without merging**
