### PR TITLE
Python: Bump py version to 0.9.1b1 for release.

### PR DESCRIPTION
**Pull request by moonbox3**
### Motivation and Context

Bump py version to 0.9.1b1 for release.

### Description

Bump py version to 0.9.1b1 for release. Update notebooks.

### Contribution Checklist

- [X] The code builds clean without any errors or warnings
- [X] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [X] All unit tests pass, and I have added new tests where possible
- [X] I didn't break anyone :smile:

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/04a7981392f703778d29bcb721d932de2549cb8c/README.md">Py3.8 Test Coverage</a><details><summary>Python 3.8 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>4805</b></td><td><b>927</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.8 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1026 | 11 :zzz: | 0 :x: | 0 :fire: | 15.321s :stopwatch: |

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/04a7981392f703778d29bcb721d932de2549cb8c/README.md">Py3.9 Test Coverage</a><details><summary>Python 3.9 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>4942</b></td><td><b>920</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.9 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1026 | 2 :zzz: | 0 :x: | 0 :fire: | 21.347s :stopwatch: |

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/04a7981392f703778d29bcb721d932de2549cb8c/README.md">Py3.11 Test Coverage</a><details><summary>Python 3.11 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>4948</b></td><td><b>919</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.11 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1026 | 1 :zzz: | 0 :x: | 0 :fire: | 15.947s :stopwatch: |

**Review by juliomenendez — APPROVED** [review]

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/04a7981392f703778d29bcb721d932de2549cb8c/README.md">Py3.10 Test Coverage</a><details><summary>Python 3.10 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>4948</b></td><td><b>919</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.10 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1026 | 1 :zzz: | 0 :x: | 0 :fire: | 18.823s :stopwatch: |

**Review by alliscode — APPROVED** [review]

**Pull request merged**
