### PR TITLE
Python: Issue 2431

### PR DESCRIPTION
**Pull request by a-little-srdjan**
### Motivation and Context

This is an implementation for #2431  

The echo completion service allows for easier unit testing of prompt constructions (e.g. through skill chaining), and a way to easier debug prompt construction issues.

The key motivation for writing up this echo is because the final prompt is constructed by _function delegate within SKFunction that does not record constructed prompts. Thus they are not available for introspection.

### Description

The changes are minimal, the introduced classes satisfy the Base interface and simply echo back the prompt.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by a-little-srdjan** [comment]
@microsoft-github-policy-service agree

**Comment by lemillermicrosoft** [comment]
Thanks again for the PR @a-little-srdjan -- I'm going to mark it as Draft for now until we get confirmation in the issue #2431 that this is something we want to make available by default. I definitely understand the desire, I've built this myself in my projects. But we may not choose to ship this in the core kernel. cc @shawncal

**Comment by a-little-srdjan** [comment]
hey @lemillermicrosoft of course.  To your point, I've had to do it a few times as well, so that internally we can post the prompts to OpenAI wrapper APIs, hence the idea. Nevertheless, pausing on this makes perfect sense. I was also thinking if it makes more sense to move the code under test module that way it is clearer that it is not some sort of a core functionality.

Thanks again for the write up

**Comment by evchaki** [comment]
@moonbox3 can you see if this is something that is still needed.

**Comment by moonbox3** [comment]
Closing this PR as we are going to use pre/post hooks to support this. Thank you for your effort, @a-little-srdjan!

**Pull request closed without merging**
