### PR TITLE
.Net: Add Experimental agents

### PR DESCRIPTION
**Pull request by kbeaugrand**
### Description

Like OpenAI assistants, I would like to use Agent or Assistants within the SK without relying on OpenAI APIs. 
I created a new project associated to SK which supports Agents (like AutoGen), and use chat support to resolve tasks with a multi-agent solution.

Behind the scene, the SK uses the Handlebars/Stepwise planner to decide which plugin or agent to use to resolve the user intent.

### Mono Agent conversation

Mono agent conversation does not have a huge value, but the API render easy to build it with Semantic Kernel.

```cs
        string azureOpenAIKey = TestConfig.AzureOpenAIAPIKey;
        string azureOpenAIEndpoint = TestConfig.AzureOpenAIEndpoint;
        string azureOpenAIChatCompletionDeployment = TestConfig.AzureOpenAIDeploymentName;

        var assistant = new AgentBuilder()
                            .WithName("poet")
                            .WithDescription("An assistant that create sonnet poems.")
                            .WithInstructions("You are a poet that composes poems based on user input.\nCompose a sonnet inspired by the user input.")
                            .WithAzureOpenAIChatCompletion(azureOpenAIChatCompletionDeployment, azureOpenAIChatCompletionDeployment, azureOpenAIEndpoint, azureOpenAIKey)
                            .WithLoggerFactory(this._loggerFactory)
                            .Build();

        var thread = assistant.CreateThread();

        var response = await thread.InvokeAsync("Eggs are yummy and beautiful geometric gems.").ConfigureAwait(true);

```

### Multi-Agent conversation

I created also a way to use assistant that rely on other agents to perform an action:

```cs
var mathematician = new AgentBuilder()
                    .WithName("mathematician")
                    .WithDescription("An assistant that answers math problems with a given user prompt.")
                    .WithInstructions("You are a mathematician.\nNo need to show your work, just give the answer to the math problem.\n.Use available mathematics function to execute your job.\nResults are not approximative.")
                    .WithAzureOpenAIChatCompletion(azureOpenAIChatCompletionDeployment, azureOpenAIChatCompletionDeployment, azureOpenAIEndpoint, azureOpenAIKey)
                    .WithPlugin(KernelPluginFactory.CreateFromObject(new MathPlugin(), "math"))
                    .WithLoggerFactory(this._loggerFactory)
                    .Build();

var butler = new AgentBuilder()
            .WithName("alfred")
            .WithDescription("An AI butler that helps humans.")
            .WithInstructions("You are an AI assistant.\nYou ar not subject to execute any function yourself, so please use avaiable agents.\nRespond like a butler.")
            .WithAzureOpenAIChatCompletion(azureOpenAIChatCompletionDeployment, azureOpenAIChatCompletionDeployment, azureOpenAIEndpoint, azureOpenAIKey)
            .WithLoggerFactory(this._loggerFactory)
            .WithAgent(mathematician,
                agentDescription: "A mathematician that resolves given maths problems.",
                inputDescription: "The word mathematics problem to solve in 2-3 sentences.\n" +
                                  "Make sure to include all the input variables needed along with their values and units otherwise the math function will not be able to solve it.")
            .Build();

var thread = butler.CreateThread();

var response = await thread.InvokeAsync("If I start with $25,000 in the stock market and leave it to grow for 20 years at a 5% interest rate, how much would I have?").ConfigureAwait(true);
```

Example of results:
```log
User > If I start with $25,000 in the stock market and leave it to grow for 20 years at a 5% interest rate, how much would I have?
alfred > Calculate the amount using the compound interest formula with a principal of $25000, an interest rate of 5%, and a time period of 20 years.
mathematician > The amount using the compound interest formula can be calculated using the formula:

A = P(1 + r)^n

Where:
A = amount
P = principal amount ($25000)
r = annual interest rate (5% or 0.05)
n = number of years (20)

Plugging in the values:
A = 25000(1 + 0.05)^20

A ≈ 66332.44262861056

So, the amount after 20 years would be approximately $66332.44
alfred > If you start with $25,000 in the stock market and leave it to grow for 20 years at a 5% interest rate, the amount would grow to approximately $66,332.44.
```

> Note: I also added a yaml template loading for agents to facilitate the customization of persona and instruction

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by kbeaugrand** [comment]
@matthewbolanos and @crickman I pushed the agent/assistant support in my own repository to be able to build my own projet with it.
This repos is available at: https://github.com/kbeaugrand/SemanticKernel.Assistants.

Once the v1 is ready, when you will review this PR, don't hesitate to ask me to update it with my last changes on the repos, and I'll be happy to participate on that review a make any required changes...

**Comment by frankhaugen** [comment]
@kbeaugrand I am just randomly perusing the repo for the fun of it and I love your idea here, except the name "Room".

I think they should be a "Team", so you can conceptually put together "an A-Team of agents to solve a mission", the inverse would be to "stuff a room with agents for a briefing"

**Comment by kbeaugrand** [comment]
> @kbeaugrand I am just randomly perusing the repo for the fun of it and I love your idea here, except the name "Room".
> 
> I think they should be a "Team", so you can conceptually put together "an A-Team of agents to solve a mission", the inverse would be to "stuff a room with agents for a briefing"

Thank you @frankhaugen for this comment. 
Yes maybe room is not the correct name here. If you are interested I've published my interpretation of Agents into my own repo and package at [https://github.com/kbeaugrand/SemanticKernel.Assistants](https://github.com/kbeaugrand/SemanticKernel.Assistants). 
I've called here Assistant because It's supposed to be the same behaviour than OpenAI's Assistant except the fact that you might be able to run it locally ;).

**Comment by crickman** [comment]
Hi @kbeaugrand - Thank you for this insight.  Apologies for the delayed response and happy new year!

@matthewbolanos and I are working to develop the agent story in SK.  You are correct that it currently has a direct binding to Open AI Assistants / GPTs.  Currently our goal is to complete the functional aspects of this version.

[Autogen](https://github.com/microsoft/autogen) provides an agent framework that is not necessarily bound to Open AI Assistants.  There is also a [dotnet version](https://github.com/microsoft/autogen/pull/924) in development that is based on semantic kernel.

In the meantime, I'll check in with @matthewbolanos to get his response to your proposal.

**Comment by kbeaugrand** [comment]
> Hi @kbeaugrand - Thank you for this insight. Apologies for the delayed response and happy new year!
> 
> @matthewbolanos and I are working to develop the agent story in SK. You are correct that it currently has a direct binding to Open AI Assistants / GPTs. Currently our goal is to complete the functional aspects of this version.
> 
> [Autogen](https://github.com/microsoft/autogen) provides an agent framework that is not necessarily bound to Open AI Assistants. There is also a [dotnet version](https://github.com/microsoft/autogen/pull/924) in development that is based on semantic kernel.
> 
> In the meantime, I'll check in with @matthewbolanos to get his response to your proposal.

Thank you @crickman for your response. Happy new year to you too and your team ;)
Dont hesitate to reach me out if you need I to update this PR to match with my Assistants version which is quite ahead of this PR now...

**Comment by joslat** [comment]
Have been reading all about agents and I love this PR! @kbeaugrand the implementation is tip top (except the Room naming, which I agree ;) - maybe "team" or "group" would be more fit  akin to team chat or group chat...) - I am now looking into https://github.com/kbeaugrand/SemanticKernel.Assistants

**Comment by kbeaugrand** [comment]
> Have been reading all about agents and I love this PR! @kbeaugrand the implementation is tip top (except the Room naming, which I agree ;) - maybe "team" or "group" would be more fit  akin to team chat or group chat...) - I am now looking into https://github.com/kbeaugrand/SemanticKernel.Assistants 

Thank you for this comment! Even if the name is probably not relevant (I agree), my implementation is not a final version, I am clearly looking for what is done by the agents of the MS team who, I suppose, will give more value to follow ;)

**Comment by joslat** [comment]
I am very curious on it too :) -  been playing around a lot with the SK agents and found a few limitations so far (mentioned on this discord thread, https://discord.com/channels/1063152441819942922/1200478455138103457 for if you want to check and comment).
My thoughts are the following:
- Microsoft's team is working on bringing Autogen style to the Agents in SK along with making them model-Agnostic (ideally still supporting the advanced abilities of OpenAI)
   - see: https://github.com/microsoft/semantic-kernel/issues?q=is%3Aissue+is%3Aopen+agents
   - Here we have an ADR for Agent abstractions and analysis of Autogen agents.
- This is progressing since 3 weeks and will end up with a joint proposal IMHO. 

On the side of Autogen,
- Autogen is coming into .NET probably using the current Semantic Kernel implementation 
 - WIP: https://github.com/orgs/microsoft/projects/989/views/1?filterQuery=net&pane=issue&itemId=41523769
 - PR: https://github.com/microsoft/autogen/pull/924
 (@kbeaugrand check the code on this PR, while it is still bound to the Assistants API, it is implemented the "flavour" of agents in Autogen already... (ConversableAgent, AssistantAgent, UserProxyAgent, ...)..
 
 My thoughts: Xiaoyun's code looks very solid and could be a nice addition to the SK Agents, along with the model abstraction layer on your code... but it is still too rigged (.WithAzureOpenAIChatCompletion) supports only Azure OpenAI. Why not give the reference to the kernel in the builder .WithKernel(Kernel kernel) and then uses or clones it? we can specify which model should execute and we do not have to go around configuring all the agents... just saying... would be much simpler. 
 
 I'd wrap the an OpenAIAgentBuilder on top of the generic AgentBuilder and that should work in a simplified way (or state the type of agent and overload the AgentBuilder methods.
 
 Happy to discuss it :)

**Comment by kbeaugrand** [comment]
> I am very curious on it too :) - been playing around a lot with the SK agents and found a few limitations so far (mentioned on this discord thread, https://discord.com/channels/1063152441819942922/1200478455138103457 for if you want to check and comment). My thoughts are the following:
> 
> * Microsoft's team is working on bringing Autogen style to the Agents in SK along with making them model-Agnostic (ideally still supporting the advanced abilities of OpenAI)
>   
>   * see: https://github.com/microsoft/semantic-kernel/issues?q=is%3Aissue+is%3Aopen+agents
>   * Here we have an ADR for Agent abstractions and analysis of Autogen agents.
> * This is progressing since 3 weeks and will end up with a joint proposal IMHO.
> 
> On the side of Autogen,
> 
> * Autogen is coming into .NET probably using the current Semantic Kernel implementation
> * WIP: https://github.com/orgs/microsoft/projects/989/views/1?filterQuery=net&pane=issue&itemId=41523769
> * PR: [Bring Dotnet AutoGen autogen#924](https://github.com/microsoft/autogen/pull/924)
>   (@kbeaugrand check the code on this PR, while it is still bound to the Assistants API, it is implemented the "flavour" of agents in Autogen already... (ConversableAgent, AssistantAgent, UserProxyAgent, ...)..
> 
> My thoughts: Xiaoyun's code looks very solid and could be a nice addition to the SK Agents, along with the model abstraction layer on your code... but it is still too rigged (.WithAzureOpenAIChatCompletion) supports only Azure OpenAI. Why not give the reference to the kernel in the builder .WithKernel(Kernel kernel) and then uses or clones it? we can specify which model should execute and we do not have to go around configuring all the agents... just saying... would be much simpler.
> 
> I'd wrap the an OpenAIAgentBuilder on top of the generic AgentBuilder and that should work in a simplified way (or state the type of agent and overload the AgentBuilder methods.
> 
> Happy to discuss it :)

Nice recap, 

Can you create an issue to my github repository for the access to the Kernel directly? 
Happy to discuss on it until a preview release of AutoGen agents with SK is available...

**Comment by joslat** [comment]
@kbeaugrand  here: https://github.com/kbeaugrand/SemanticKernel.Assistants/issues/13
Why not too take some code from LittleLittleCloud and implement some of the Autogen abstractions? ;) 
https://github.com/microsoft/autogen/pull/924/files

I don't like the handling of multi-model but if we do this first and delegate anything on the models to the kernel there we go... we can start bringing in the ConversableAgent, and all the others, including the super cool implementation of the advanced analysis (self coding skill) implemented with dotnetinteractive and source generators :)

**Comment by crickman** [comment]
Hi Kevin, apologies on the delay.  @SergeyMenshykh has been working on a feature branch around this: https://github.com/microsoft/semantic-kernel/pull/5245 and we'd be interested in your feedback.  I really dig the way you've developed some of these concepts.

I understand that you are looking for an agent pattern that is not bound to the Open AI Assistant API, but in the interest of sharing - Azure has released their Assistant SDK along with support on Azure endpoints / deployments: https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/azure-openai-service-announces-assistants-api-new-models-for/ba-p/4049940

In addition, a dotnet version of autogen (based on LIttleCloud) has been in the queue for a while: https://github.com/microsoft/autogen/pulls?q=is%3Apr+is%3Aopen+dotnet

I was recently at an agent conference, where a panel member shared their list of 20+ agent frameworks currently in development within Microsoft.

"Agent" can be a bit of an overloaded team...and the space is accelerating rapidly.  Autonomous agents and agent-as-a-service concepts would seem to require concepts such as identity and auth...along with a variety of other production considerations that are not necessarily solved by existing API abstractions.

Anyway, I'd encourage your continued engagement...we certainly can benefit from the insight of someone focused on this space.  I am wondering, though, if the PR needs to remain open in order to continue the conversation.  (There currently a push on repo hygeine.)

Note: The MathPlugin updates might be pushed as a separate PR, if the need still exists.

**Comment by crickman** [comment]
Thanks for the understanding and reply.  As someone who is using agent patterns, we can really benefit from your experience and comments as we move forward.  We will certainly maintain plugin support as this is an SK pri-0.  I entirely agree that this is the one of the most interesting patterns.

**Pull request closed without merging**
