### PR TITLE
CosmosDB memory connector improvement

### PR DESCRIPTION
**Pull request by JohnMasen**
### Description

1. Use UDF for cosin simularity calculation, reduce network IO
2. Improve collection existance check performance
3. Create a base class for memory storage connectors, this make further connectors easier to test
4. Various bugs fixed (not found in issues, but found in unit tests)

I'm experienced in C#, but not experienced in Github PR. please feel free to contact me if you have any questions or suggestions about this PR.

### Contribution Checklist

- [Y] The code builds clean without any errors or warnings
- [Y] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [Y] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [Y] All unit tests pass, and I have added new tests where possible
- [Y] I didn't break anyone :smile:

### CODE REVIEW

**Comment by JohnMasen** [comment]
@microsoft-github-policy-service agree

**Comment by lemillermicrosoft** [comment]
> Seems the file Connectors.Memory.CosmosDB.csproj was broken after manually solve conflict. Any thing I can do to fix this?

I think the a good thing to do is mark this as draft until CI gates are passing. It might be more useful to file as issue if assistance is needed.

**Comment by JohnMasen** [comment]
Hi, seems some class files are NOT included in the project file "Connectors.Memory.CosmosDB.csproj".  The possible reason is my code base did not synced with lastest.
Anyway to fix this?
Or I can try create a new PR and abandon this one, please tell me if you need to redo the PR.

**Comment by awharrison-28** [comment]
> Hi, seems some class files are NOT included in the project file "Connectors.Memory.CosmosDB.csproj". The possible reason is my code base did not synced with lastest. Anyway to fix this? Or I can try create a new PR and abandon this one, please tell me if you need to redo the PR.

@JohnMasen Please ensure your PR branch builds and passes tests. You can resolve it in whatever fashion you want - copying files in conflict over from main and resolving locally may be less work than starting from a fresh branch.

**Comment by JohnMasen** [comment]
> > Hi, seems some class files are NOT included in the project file "Connectors.Memory.CosmosDB.csproj". The possible reason is my code base did not synced with lastest. Anyway to fix this? Or I can try create a new PR and abandon this one, please tell me if you need to redo the PR.
> 
> @JohnMasen Please ensure your PR branch builds and passes tests. You can resolve it in whatever fashion you want - copying files in conflict over from main and resolving locally may be less work than starting from a fresh branch.

Hi, I found the cosmosDB unit tests are failed because of CosmosDB unit test requires local cosmosDB emulator.  The previous version does not have unit tests. Seems I have to disable the the unit tests for this PR.

**Comment by JohnMasen** [comment]
> > Hi, seems some class files are NOT included in the project file "Connectors.Memory.CosmosDB.csproj". The possible reason is my code base did not synced with lastest. Anyway to fix this? Or I can try create a new PR and abandon this one, please tell me if you need to redo the PR.
> 
> @JohnMasen Please ensure your PR branch builds and passes tests. You can resolve it in whatever fashion you want - copying files in conflict over from main and resolving locally may be less work than starting from a fresh branch.

@awharrison-28 the conflicts are solved, PR is ready for review.

**Comment by JohnMasen** [comment]
> > > Hi, seems some class files are NOT included in the project file "Connectors.Memory.CosmosDB.csproj". The possible reason is my code base did not synced with lastest. Anyway to fix this? Or I can try create a new PR and abandon this one, please tell me if you need to redo the PR.
> > 
> > 
> > @JohnMasen Please ensure your PR branch builds and passes tests. You can resolve it in whatever fashion you want - copying files in conflict over from main and resolving locally may be less work than starting from a fresh branch.
> 
> @awharrison-28 the conflicts are solved, PR is ready for review.

hi @awharrison-28, I found the merge failed the integration tests. as the cosmosDB requires a real cosmosDB account or a local cosmosDB emulator(Windows only), is there anyway we can add a valid CosmosDB configuration to the integration environment?

**Comment by JohnMasen** [comment]
Closing this PR due to cosmosDB connector is deprecated.

**Pull request closed without merging**
