### PR TITLE
Python: Fix windows runtime error: adapt asyncio event loop policy for windows python 3.10 and above

### PR DESCRIPTION
**Pull request by imfuli**
… windows

### Motivation and Context

To fix a runtime error on windows for python version 3.10, 3.11 and above

On windows, python version above 3.10.1, there will be a runtime error caused by asyncio event loop. add adapting code for windows when python version is above 3.10.1 to avoid the error.

### Description

Without this fix, the example script will runinto a runtime error, shows as below:

'''
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000289E4B2C550>
Traceback (most recent call last):
  File "C:\Program Files\Python3.10\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\Python3.10\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python3.10\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Program Files\Python3.10\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
'''

The change only handle windows platform and python version above 3.10.1.

Refer link:

https://docs.python.org/3/library/asyncio-policy.html

"Note In Python versions 3.10.9, 3.11.1 and 3.12 the [get_event_loop()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop) method of the default asyncio policy emits a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) if there is no running event loop and no current loop is set. In some future Python release this will become an error."

Note: per testing, this error also occurred on python 3.10 below 3.10.9

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Review by mkarle — CHANGES_REQUESTED** [review]
So I've noticed this problem occurring too. However, I see it in versions >= 3.8 but <= 3.10.1.  I ran the unit tests with 3.8 and get the same Runtime error but with 3.10.11, I do not.

**Review by imfuli — COMMENTED** [review]
updated per Mark's comment on the python version to be adapted.

**Comment by imfuli** [comment]
@mkarle Hello Mark, I've updated the fix, please go ahead the review? thanks.

**Review by mkarle — APPROVED** [review]

**Review by mkarle — APPROVED** [review]
Needed to lower the version to 3.8.0

**Review by mkarle — APPROVED** [review]

**Pull request merged**
