### PR TITLE
.Net: Fix redis package reference

### LINKED ISSUE #2953: Could not load file or assembly `Microsoft.Bcl.AsyncInterfaces` exception
**Describe the bug**

Could not load file or assembly `Microsoft.Bcl.AsyncInterfaces` exception when using the redis memory storage

**To Reproduce**

``` c#
var apiEndpoint = Guard.NotNullOrEmpty(Environment.GetEnvironmentVariable("AZURE_OPENAI_API_ENDPOINT"));
var apiKey = Guard.NotNullOrEmpty(Environment.GetEnvironmentVariable("AZURE_OPENAI_API_KEY"));
var kernelBuilder = new KernelBuilder();
kernelBuilder.WithAzureChatCompletionService("gpt-35-turbo", apiEndpoint, apiKey);
kernelBuilder.WithAzureTextEmbeddingGenerationService("text-embedding-ada-002", apiEndpoint, apiKey);
// kernelBuilder.WithMemoryStorage(new VolatileMemoryStore());
kernelBuilder.WithMemoryStorage(new RedisMemoryStore("localhost:6379"));
var kernel = kernelBuilder.Build();
var collectionName = "Products";
await using var fs = File.OpenRead("text-sample.json");
var list = await JsonSerializer.DeserializeAsync<Product[]>(fs);
Guard.NotNull(list);
foreach (var product in list)
{
    await kernel.Memory.SaveInformationAsync(collectionName, product.Description, product.Title, product.Description, product.Category);
}


file sealed class Product
{
    [JsonPropertyName("id")]
    public required string Id { get; set; }
    
    [JsonPropertyName("category")]
    public required string Category { get; set; }
    
    [JsonPropertyName("title")]
    public required string Title { get; set; }
    
    [JsonPropertyName("content")]
    public required string Description { get; set; }
}

```

**Expected behavior**

success without exception

**Screenshots**

image

**Platform**
 - OS: Windows
 - IDE:  VS Code
 - Language: C#
 - Source: 

```
<PackageVersion Include="Microsoft.SemanticKernel" Version="0.24.230918.1-preview" />
<PackageVersion Include="Microsoft.SemanticKernel.Connectors.Memory.Redis" Version="0.24.230918.1-preview" />
```

**Additional context**

Without exception when using the memory storage such as `VolatileMemoryStore`

### PR DESCRIPTION
**Pull request by JadynWong**
### Motivation and Context
Fix #2953

### Description
Looks like, since #1799, there's been a problem. However, due to references from other projects, tests and samples have not shown the problem. 

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by JadynWong** [comment]
Is there a better way to solve this problem?

Tested with a simple project, works fine with .net7.0 and .net8.0.

```csharp
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.Memory.Redis;
using sk_redis_test;

var apiEndpoint = Env.Var("AzureOpenAI:Endpoint");
var apiKey = Env.Var("AzureOpenAI:ApiKey");
var kernelBuilder = new KernelBuilder();
kernelBuilder.WithAzureChatCompletionService("gpt-35-turbo", apiEndpoint, apiKey);
kernelBuilder.WithAzureTextEmbeddingGenerationService("text-embedding-ada-002", apiEndpoint, apiKey);
using var memoryStore = new RedisMemoryStore("localhost:6379");
kernelBuilder.WithMemoryStorage(memoryStore);
var kernel = kernelBuilder.Build();

var collectionName = "test";

for (int i = 1; i <= 10; i++)
{
    var key = await kernel.Memory.SaveInformationAsync(collectionName, i.ToString(), i.ToString(), i.ToString(), i.ToString());
    Console.WriteLine(key);
}

await memoryStore.DeleteCollectionAsync(collectionName);
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>sk_redis_test</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>5ee045b0-aea3-4f08-8d31-32d1a6f8fed0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Connectors\Connectors.AI.OpenAI\Connectors.AI.OpenAI.csproj" />
    <ProjectReference Include="..\src\Connectors\Connectors.Memory.Redis\Connectors.Memory.Redis.csproj" />
  </ItemGroup>

</Project>
  ```

**Comment by dmytrostruk** [comment]
@JadynWong Thanks for quick fix! Yes, we have similar problem in other packages as well. Looks like `NRedisStack` depends on `System.Text.Json >= 7.0.2` which depends on `Microsoft.Bcl.AsyncInterfaces >= 7.0.0`, so there is version mismatch.

> Is there a better way to solve this problem?

Usually, you can just specify concrete package version where it's needed, like this:
```
<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="7.0.0" />
```

But with central package management it's not allowed to specify version in `PackageReference` attribute, so we need to use `PackageVersion` instead:
```
<PackageVersion Update="Microsoft.Bcl.AsyncInterfaces" Version="7.0.0" />
```

We use similar approach in other existing packages as well.

@JadynWong Did you try to remove the line with package version update and verify that issue can be reproduced in your scenario with simple project .net7.0/.net8.0, and then when you add it back, the issue is resolved?

**Comment by JadynWong** [comment]
I reproduced the issue in the simple project using the same approach as you described. When adding `Microsoft.Bcl.AsyncInterfaces` and set the version to 7.0.0, the issue was solved.

**Comment by dmytrostruk** [comment]
> @dmytrostruk Yes. I reproduced the issue in the simple project using the same approach as you described. When adding `Microsoft.Bcl.AsyncInterfaces` and set the version to 7.0.0, the issue was solved.

@JadynWong Sounds awesome, thank you!

**Review by SergeyMenshykh — APPROVED** [review]

**Pull request merged**
