### PR TITLE
.Net: OpenAI V2 & Assistants V2 - GA 

### PR DESCRIPTION
**Pull request by crickman**
Accumulation of incremental changes that were reviewed separately.

This change fundamentally grapples with updating the Azure AI OpenAI SDK from V1 to V2. 

This involves:
- Including the OpenAI SDK dependency
- Refactoring the OpenAI Connector
- Introducing an Azure OpenAI Connector
- Update the experimental `Agents.OpenAI` to support V2 assistant features (breaking change)

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
@crickman Can you provide a description of the changes you are making. Also it would be better if the PR targeted https://github.com/microsoft/semantic-kernel/tree/feature-connectors-openai so we can see your changes.

**Comment by crickman** [comment]
> @crickman Can you provide a description of the changes you are making. Also it would be better if the PR targeted https://github.com/microsoft/semantic-kernel/tree/feature-connectors-openai so we can see your changes.

@markwallace-microsoft  -This is the connector work for @SergeyMenshykh and @RogerBarreto.  This PR just provides visibility / diff.

**Comment by crickman** [comment]
Merged from main with note: Excluded new demo StepwisePlannerMigration from build

**Review by RogerBarreto — CHANGES_REQUESTED** [review]
No ETA for merging ATM.

**Review by markwallace-microsoft — APPROVED** [review]

**Review by dmytrostruk — APPROVED** [review]

**Review by RogerBarreto — APPROVED** [review]

**Review by RogerBarreto — APPROVED** [review]

**Review by markwallace-microsoft — APPROVED** [review]

**Review by markwallace-microsoft — APPROVED** [review]

**Review by markwallace-microsoft — APPROVED** [review]

**Comment by arynaq** [comment]
Yai, looks promising, been looking forward to using agents (for cases where data sensitivity is not an issue, I wish MS gave an indepth insight into how persistence is handled for threads and agents so my data officer can get some sleep)

**Pull request merged**
