### PR TITLE
Python: Refactoring. Use get_function and get_plugin.

### PR DESCRIPTION
**Pull request by stefan521**
### Motivation and Context

Refactoring some of the code following [this advice](https://github.com/microsoft/semantic-kernel/pull/6371#discussion_r1611138252) from the maintainers.

### Description

Look up kernel functions and plugins with the `get_function` and `get_plugin` method. Removed the unused `DEFAULT_CHAT_SYSTEM_PROMPT`

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by stefan521** [comment]
@microsoft-github-policy-service agree [company=""]

**Comment by stefan521** [comment]
@microsoft-github-policy-service agree

**Comment by stefan521** [comment]
@microsoft-github-policy-service agree

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/dba99ca4a6210631a6ebad42b43b5f5d3e8600a7/README.md">Py3.10 Test Coverage</a><details><summary>Python 3.10 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>6077</b></td><td><b>869</b></td><td><b>86%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.10 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1374 | 1 :zzz: | 0 :x: | 0 :fire: | 14.081s :stopwatch: |

**Review by moonbox3 — APPROVED** [review]
LGTM. My small nit is to use named args to make it more clear when reading:

`function = kernel.get_function(plugin_name=<name>, function_name=<name>)`

May just be my style preference. :)

**Comment by stefan521** [comment]
> LGTM. My small nit is to use named args to make it more clear when reading:
> 
> `function = kernel.get_function(plugin_name=<name>, function_name=<name>)`
> 
> May just be my style preference. :)

That's a good shout. I've named them.

**Comment by moonbox3** [comment]
@stefan521 please run a `Black` format in the python directory to fix the lint issues.

**Review by eavanvalkenburg — APPROVED** [review]

**Pull request merged**
