### PR TITLE
Python: hf sample and generator

### PR DESCRIPTION
**Pull request by eavanvalkenburg**
### Motivation and Context

Adds a parameter to the hugging face text completion class to supply the Pipeline, this allows more customization.
Added a sample that shows how to setup quantization for HF models. Not ready to use because of differences in setup and hardware.

Closes: #6374 

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/f50e230e1b29d375c21e077ebc4e557770bf796e/README.md">Py3.10 Test Coverage</a><details><summary>Python 3.10 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/connectors/ai/hugging_face/services</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/f50e230e1b29d375c21e077ebc4e557770bf796e/python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_completion.py">hf_text_completion.py</a></td><td>43</td><td>14</td><td>67%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/f50e230e1b29d375c21e077ebc4e557770bf796e/python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_completion.py#L92-L93">92&ndash;93</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/f50e230e1b29d375c21e077ebc4e557770bf796e/python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_completion.py#L95">95</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/f50e230e1b29d375c21e077ebc4e557770bf796e/python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_completion.py#L121-L144">121&ndash;144</a></td></tr><tr><td><b>TOTAL</b></td><td><b>6529</b></td><td><b>727</b></td><td><b>89%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python 3.10 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1547 | 1 :zzz: | 0 :x: | 0 :fire: | 24.262s :stopwatch: |

**Comment by matthewbolanos** [comment]
@eavanvalkenburg, are you still working on this one? Or should we close it out?

**Comment by eavanvalkenburg** [comment]
@matthewbolanos still want to add this, just has not been a prio, it adds some additional capabilities to the connector as well as a new sample

**Comment by moonbox3** [comment]
Please re-open if/when we want to get this into main.

**Pull request closed without merging**
