### PR TITLE
.Net: Feature function calling

### PR DESCRIPTION
**Pull request by Kevdome3000**
### Motivation and Context
 I've observed many requests for function calling on the .Net side but haven't seen any movement so I'm submitting this PR with the hopes of spurring some activity on the development function call support.

- Allows users to pass FunctionDefinitions in Completion requests and receive raw json responses or deserialize the response to the model of choice
- Also introduces a new implementation of planners in a project called Structured Planners which uses FunctionCalling instead of string manipulation to create plans

### Description
This PR adds the ability to pass FunctionDefinitions in Chat Completion requests and introduces a new set of Planners that use function calling to create plans.

new features:

- SKFunctionCall - initialized like a SemanticFunction with additional properties to manage FunctionDefinitions
- FunctionCallResult - a class containing the function call response from OpenAI
- OpenAIChatRequestSettings - extends ChatRequestSettings with two additional properties, FunctionCall and CallableFunctions
- Extensions methods that seamlessly convert FunctionView to FunctionDefnition so no additional work is needed from the user
- StucturedActionPlanner - ActionPlanner implementation with much less token usage
- StucturedSequntialPlanner - SequentialPlanner implementation which is more reliable with using far less tokens
- StructuredStepwisePlanner - StepwisePlanner implementation that uses function calling and chat history resulting in fewer steps taken, less token usage, and much less code

In early tests the structured planners out perform the current implementation of all planners in accuracy, token usage, reliability, and time of execution.

modifications:
- a simple change made to ChatResult that allows for the detection of function call responses
- a simple change to ClientBase that allows for the detection of OpenAIChatRequest settings and passes the FunctionCall and FunctionDefinitions to theChatCompletionOptions
- added examples to KernelSyntaxExamples

Since FunctionCalling is an OpenAI concept, I didn't think it made sense to integrate deeper and made all changes in the OpenAi.Connectors project.

I can add integration tests if needed

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by gitri-ms** [comment]
Hi @Kevdome3000 - thank you for this PR. I put this comment in the issue (#1450) but will reiterate here as well:

We on the SK team have been having in-depth design discussions to determine how this capability fits into the greater architectural vision for SK. These conversations are still ongoing, and we are evaluating several different approaches and design questions (including those presented through this PR).

I hope to have more clarity on the architectural direction we want to take within the next week, so until then I am marking this PR as draft and will follow up.

**Comment by Kevdome3000** [comment]
> Hi @Kevdome3000 - thank you for this PR. I put this comment in the issue (#1450) but will reiterate here as well:
> 
> We on the SK team have been having in-depth design discussions to determine how this capability fits into the greater architectural vision for SK. These conversations are still ongoing, and we are evaluating several different approaches and design questions (including those presented through this PR).
> 
> I hope to have more clarity on the architectural direction we want to take within the next week, so until then I am marking this PR as draft and will follow up.

Ok sounds good, thanks for the update!

**Comment by benm5678** [comment]
@Kevdome3000 Nice!! Very curious to try, is there an example usage with native function calls?  Thanks!!

**Comment by Kevdome3000** [comment]
> @Kevdome3000 Nice!! Very curious to try, is there an example usage with native function calls via the StructuredStepwisePlanner? Thanks!!

Yea, it's in the KernelSyntaxExamples Example51_StepwisePlannerExample

**Comment by gitri-ms** [comment]
Closing in favor of #2842 as our initial .NET implementation of OpenAI function calling.

However, we are continuing to explore how we can further integrate function calling into SK via the kernel and/or planner, beyond this initial implementation. We may circle back to this PR in the future to inform our updates to this feature. Thank you again!

**Pull request closed without merging**
