### PR TITLE
new skill/plugin suggestion

### PR DESCRIPTION
**Pull request by rom212**
### Motivation and Context

I created this skill/plugin to illustrate some capabilities in a blog post. It turns out, this skill works well and I thought we could add to the sample library. 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by Krzysztof318** [comment]
How effective (%) is that prompt on many different examples? Did you do tests? I think this prompt is too general.

**Comment by rom212** [comment]
> How effective (%) is that prompt on many different examples? Did you do tests? I think this prompt is too general and requires more specific to add that plugin to kernel.

It scores 100% on this test set: https://github.com/rom212/semantic_skill_evaluation/blob/master/batchdata.jsonl

By comparison, it's not less specific than the other two that already exist in the kernel for classification use cases (question and importance).

Did you find that it was not working well?

**Comment by Krzysztof318** [comment]
I wasn't testing this yet. Makes me wonder how it would work as an extra layer for example when filtering an email just after the spam assasin layer.

**Comment by markwallace-microsoft** [comment]
@rom212 Thanks for the PR but this has been inactive for a while and the code is out of sync with latest Semantic Kernel patterns. If you are interested in updating this please take a look at the current sample plugins https://github.com/microsoft/semantic-kernel/tree/main/samples/plugins

**Pull request closed without merging**
