### PR TITLE
Java: Fix spotless apply and restrict format automation

### PR DESCRIPTION
**Pull request by Luigi96**
### Description

- Fix spotless apply that wasn't able to make changes to the PR.
- Restrict Java Format Automation to be triggered just by the author and the Semantic Kernel Java Team.

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Review by markwallace-microsoft — CHANGES_REQUESTED** [review]
Change looks good but the PR needs to target the main branch. The java branch gets updated with the latest from main on a regular basis.

**Comment by brunoborges** [comment]
@Luigi96 can you please work with @johnoliver to review this PR?

**Comment by evchaki** [comment]
@johnoliver  does this one look ready?

**Pull request closed without merging**
