### PR TITLE
Removed CallerArgumentExpressionAttribute to fix support for dotnet 6

### PR DESCRIPTION
**Pull request by adrianwyatt**
### Motivation and Context
Build was failing on systems with dotnet 6 installed (and not dotnet 7)

### Description
Removed CallerArgumentExpressionAttribute and its usage.

### CODE REVIEW

**Review by dluc — APPROVED** [review]

**Comment by dluc** [comment]
THANKS! We need CI on .NET6 only systems (and cross-platform code reviewers)

**Comment by stephentoub** [comment]
This should not fail. It's supported by C# 10 /.NET 6. What exactly is failing?

**Comment by adrianwyatt** [comment]
> This should not fail. It's supported by C# 10 / .NET 6. It even works when targeting .NET Framework. What exactly is failing?
> 
> (Also, if you just remove this it's going to remove all of the parameter names from ArgumentExceptions that get thrown.)

https://github.com/microsoft/semantic-kernel/issues/871 - let's get it working and we can re-implement a dotnet6 compatible version after.

**Comment by adrianwyatt** [comment]
> THANKS! We need CI on .NET6 only systems (and cross-platform code reviewers)

Our PR/CI builds say they are .NET6 but apparently not quite? It's not apparent why PR/CI passes at the moment.

**Review by dluc — APPROVED** [review]

**Comment by stephentoub** [comment]
Please don't submit this.

Just change the `nameof(obj)` to `"obj"`.

**Comment by adrianwyatt** [comment]
> Please don't submit this.
> 
> Just change the `nameof(obj)` to `"obj"` (more specifically the name of the first parameter as a string).
> 
> Whoever is hitting this has an outdated C# compiler.

Updated with your suggestion and looks good - thanks!

**Review by dluc — APPROVED** [review]

**Pull request merged**
