### PR TITLE
Python: Fix action planner

### PR DESCRIPTION
**Pull request by eavanvalkenburg**
### Motivation and Context

Got a report of a bug in the action planner creation, fixed here.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Review by moonbox3 — APPROVED** [review]

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/README.md">Python Test Coverage</a><details><summary>Python Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/planners/action_planner</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py">action_planner.py</a></td><td>115</td><td>22</td><td>81%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py#L11">11</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py#L106">106</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py#L115">115</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py#L128">128</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py#L132-L133">132&ndash;133</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py#L143-L150">143&ndash;150</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py#L162">162</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py#L187">187</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py#L245-L246">245&ndash;246</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py#L263">263</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/action_planner/action_planner.py#L280-L291">280&ndash;291</a></td></tr><tr><td colspan="5"><b>semantic_kernel/planners/stepwise_planner</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py">stepwise_planner.py</a></td><td>224</td><td>139</td><td>38%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L12">12</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L104">104</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L118-L136">118&ndash;136</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L145-L214">145&ndash;214</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L235-L238">235&ndash;238</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L246-L257">246&ndash;257</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L260">260</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L268-L283">268&ndash;283</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L286-L322">286&ndash;322</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L325-L353">325&ndash;353</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L356-L361">356&ndash;361</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L364-L376">364&ndash;376</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L379-L382">379&ndash;382</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L395-L407">395&ndash;407</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ee8eb72a6e8d4f80e6cbebbc9931f99b6776efbf/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L410">410</a></td></tr><tr><td><b>TOTAL</b></td><td><b>4871</b></td><td><b>1046</b></td><td><b>79%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 991 | 11 :zzz: | 0 :x: | 0 :fire: | 25.237s :stopwatch: |

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/README.md">Python Test Coverage</a><details><summary>Python Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/planners/action_planner</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py">action_planner.py</a></td><td>115</td><td>22</td><td>81%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py#L11">11</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py#L106">106</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py#L115">115</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py#L128">128</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py#L132-L133">132&ndash;133</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py#L143-L150">143&ndash;150</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py#L162">162</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py#L187">187</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py#L245-L246">245&ndash;246</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py#L263">263</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/action_planner/action_planner.py#L280-L291">280&ndash;291</a></td></tr><tr><td colspan="5"><b>semantic_kernel/planners/stepwise_planner</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py">stepwise_planner.py</a></td><td>224</td><td>139</td><td>38%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L12">12</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L104">104</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L118-L136">118&ndash;136</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L145-L214">145&ndash;214</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L235-L238">235&ndash;238</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L246-L257">246&ndash;257</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L260">260</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L268-L283">268&ndash;283</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L286-L322">286&ndash;322</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L325-L353">325&ndash;353</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L356-L361">356&ndash;361</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L364-L376">364&ndash;376</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L379-L382">379&ndash;382</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L395-L407">395&ndash;407</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/8b04eb7d0533a7874b0e9c10266dd71fef0823db/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L410">410</a></td></tr><tr><td><b>TOTAL</b></td><td><b>4871</b></td><td><b>1040</b></td><td><b>79%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 993 | 11 :zzz: | 0 :x: | 0 :fire: | 21.498s :stopwatch: |

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/README.md">Python Test Coverage</a><details><summary>Python Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/planners/action_planner</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py">action_planner.py</a></td><td>115</td><td>22</td><td>81%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py#L11">11</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py#L106">106</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py#L115">115</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py#L128">128</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py#L132-L133">132&ndash;133</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py#L143-L150">143&ndash;150</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py#L162">162</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py#L187">187</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py#L245-L246">245&ndash;246</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py#L263">263</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/action_planner/action_planner.py#L280-L291">280&ndash;291</a></td></tr><tr><td colspan="5"><b>semantic_kernel/planners/stepwise_planner</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py">stepwise_planner.py</a></td><td>224</td><td>139</td><td>38%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L12">12</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L104">104</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L118-L136">118&ndash;136</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L145-L214">145&ndash;214</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L235-L238">235&ndash;238</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L246-L257">246&ndash;257</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L260">260</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L268-L283">268&ndash;283</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L286-L322">286&ndash;322</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L325-L353">325&ndash;353</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L356-L361">356&ndash;361</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L364-L376">364&ndash;376</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L379-L382">379&ndash;382</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L395-L407">395&ndash;407</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/2fa1ea1f71d32624887b979176a2efd37dd189ab/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L410">410</a></td></tr><tr><td><b>TOTAL</b></td><td><b>4871</b></td><td><b>1040</b></td><td><b>79%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 993 | 11 :zzz: | 0 :x: | 0 :fire: | 25.211s :stopwatch: |

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/README.md">Python Test Coverage</a><details><summary>Python Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/planners/action_planner</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py">action_planner.py</a></td><td>115</td><td>22</td><td>81%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py#L11">11</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py#L106">106</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py#L115">115</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py#L128">128</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py#L132-L133">132&ndash;133</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py#L143-L150">143&ndash;150</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py#L162">162</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py#L187">187</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py#L245-L246">245&ndash;246</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py#L263">263</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/action_planner/action_planner.py#L280-L291">280&ndash;291</a></td></tr><tr><td colspan="5"><b>semantic_kernel/planners/stepwise_planner</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py">stepwise_planner.py</a></td><td>224</td><td>139</td><td>38%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L12">12</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L104">104</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L118-L136">118&ndash;136</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L145-L214">145&ndash;214</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L235-L238">235&ndash;238</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L246-L257">246&ndash;257</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L260">260</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L268-L283">268&ndash;283</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L286-L322">286&ndash;322</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L325-L353">325&ndash;353</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L356-L361">356&ndash;361</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L364-L376">364&ndash;376</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L379-L382">379&ndash;382</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L395-L407">395&ndash;407</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3c8ce41af3564e6ffef34baf98671244f34bc5c2/python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py#L410">410</a></td></tr><tr><td><b>TOTAL</b></td><td><b>4871</b></td><td><b>1040</b></td><td><b>79%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 993 | 11 :zzz: | 0 :x: | 0 :fire: | 25.371s :stopwatch: |

**Pull request merged**
