### PR TITLE
Python: Fixed unnecessary slashes in URLs

### PR DESCRIPTION
**Pull request by ymuichiro**
### Motivation and Context

Extra slashes are inserted in endpoint. openai-python receives endpoint as a string and adds one slash.
Due to the omission of string formatting, processing using rstrip was added.

```
OK: endpoint ... `http://127.0.0.1/openai/deployments/~`
NG: endpoint ... `http://127.0.0.1//openai/deployments/~`
```

### Description
https://github.com/microsoft/semantic-kernel/issues/5236

### Contribution Checklist

- [*] The code builds clean without any errors or warnings
- [*] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [*] All unit tests pass, and I have added new tests where possible
- [*] I didn't break anyone :smile:

### CODE REVIEW

**Review by eavanvalkenburg — APPROVED** [review]

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/82c377b668a281ea8aa72b5c7324bbca8ef47dae/README.md">Python Test Coverage</a><details><summary>Python Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/connectors/ai/open_ai/services</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/82c377b668a281ea8aa72b5c7324bbca8ef47dae/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py">azure_config_base.py</a></td><td>34</td><td>2</td><td>94%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/82c377b668a281ea8aa72b5c7324bbca8ef47dae/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py#L80">80</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/82c377b668a281ea8aa72b5c7324bbca8ef47dae/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py#L96">96</a></td></tr><tr><td><b>TOTAL</b></td><td><b>4781</b></td><td><b>1051</b></td><td><b>78%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 978 | 11 :zzz: | 0 :x: | 0 :fire: | 18.932s :stopwatch: |

**Review by eavanvalkenburg — COMMENTED** [review]
Should this also be done for the OpenAI classes (this is for Azure OpenAI)?

**Comment by ymuichiro** [comment]
@eavanvalkenburg 

> Should this also be done for the OpenAI classes (this is for Azure OpenAI)? @ymuichiro

I don't think there is any need to change the OpenAI class. 

https://github.com/microsoft/semantic-kernel/blob/d65d3b617b848d33cc1816b1756c3cdb65f4f337/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_config_base.py#L57

`base_url` or `endpoint` is not used in "OpenAIConfigBase".
This is because the value is hardcoded into `openai-python`, or it is received from an environment variable.

https://github.com/openai/openai-python/blob/e41abf7b7dbc1e744d167f748e55d4dedfc0dca7/src/openai/_client.py#L305

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/README.md">Py3.9 Test Coverage</a><details><summary>Python 3.9 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/connectors/ai/open_ai/services</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py">azure_config_base.py</a></td><td>34</td><td>2</td><td>94%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py#L80">80</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py#L96">96</a></td></tr><tr><td><b>TOTAL</b></td><td><b>4988</b></td><td><b>939</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python 3.9 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1042 | 2 :zzz: | 0 :x: | 0 :fire: | 20.191s :stopwatch: |

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/README.md">Py3.11 Test Coverage</a><details><summary>Python 3.11 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/connectors/ai/open_ai/services</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py">azure_config_base.py</a></td><td>34</td><td>2</td><td>94%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py#L80">80</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py#L96">96</a></td></tr><tr><td><b>TOTAL</b></td><td><b>4994</b></td><td><b>937</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python 3.11 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1042 | 1 :zzz: | 0 :x: | 0 :fire: | 23.358s :stopwatch: |

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/README.md">Py3.10 Test Coverage</a><details><summary>Python 3.10 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/connectors/ai/open_ai/services</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py">azure_config_base.py</a></td><td>34</td><td>2</td><td>94%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py#L80">80</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py#L96">96</a></td></tr><tr><td><b>TOTAL</b></td><td><b>4994</b></td><td><b>937</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python 3.10 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1042 | 1 :zzz: | 0 :x: | 0 :fire: | 17.325s :stopwatch: |

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/README.md">Py3.8 Test Coverage</a><details><summary>Python 3.8 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/connectors/ai/open_ai/services</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py">azure_config_base.py</a></td><td>34</td><td>2</td><td>94%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py#L80">80</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/3974778752fafb9bf318dd051271fd5db06d290c/python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py#L96">96</a></td></tr><tr><td><b>TOTAL</b></td><td><b>4851</b></td><td><b>945</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python 3.8 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1042 | 11 :zzz: | 0 :x: | 0 :fire: | 20.446s :stopwatch: |

**Review by moonbox3 — APPROVED** [review]

**Pull request merged**
