### PR TITLE
Add debugger displays and type proxies for core abstraction types

### PR DESCRIPTION
**Pull request by stephentoub**
### Motivation and Context

Make it easier to examine core state while debugging with semantic kernel.

### Description

While debugging through examples to better understand the whole model, I found myself routinely diving into various data structures to find the information I wanted to see.  I've added [DebuggerDisplay] and [DebuggerTypeProxy] attributes to surface the most relevant information.  I view this as a starting point; hopefully folks like this and will replicate it onto other types of relevance.

Example Before

image

Example After

image

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

cc: @shawncal

### CODE REVIEW

**Review by lemillermicrosoft — APPROVED** [review]
This is cool! I might add similar to `Plan` object. Curious if you have any thoughts/consideration there.

**Comment by stephentoub** [comment]
> Curious if you have any thoughts/consideration there.

I've pushed another commit to add a debugger display for plan.  Obviously this and any other one I've added can be tweaked to ensure the most useful information is highlighted.

Before

image

After

image

**Comment by lemillermicrosoft** [comment]
> > This is cool! I might add similar to Plan object. Curious if you have any thoughts/consideration there.
> 
> I've pushed another commit to add a debugger display for plan. Obviously this and any other one I've added can be tweaked to ensure the most useful information is highlighted.
> 
> Before
> 
> image
> After
> 
> image

**Comment by lemillermicrosoft** [comment]
> > This is cool! I might add similar to Plan object. Curious if you have any thoughts/consideration there.
> 
> I've pushed another commit to add a debugger display for plan. Obviously this and any other one I've added can be tweaked to ensure the most useful information is highlighted.
> 
> Before
> 
> image
> After
> 
> image

Awesome, thank you!

**Review by lemillermicrosoft — DISMISSED** [review]
Thanks for adding Plan changes!

**Review by shawncal — APPROVED** [review]

**Comment by shawncal** [comment]
Merged main, resolved (in browser) then had to fix a dotnet format whitespace thing.

**Review by shawncal — APPROVED** [review]

**Pull request merged**
