### PR TITLE
Make use of OpenAI SDK directly

### PR DESCRIPTION
**Pull request by brunoborges**
This PR removes the Azure Open AI Client wrapper originally created as a workaround.

### CODE REVIEW

**Comment by brunoborges** [comment]
@johnoliver there it goes.

**Review by markwallace-microsoft — COMMENTED** [review]
LGTM

**Review by johnoliver — DISMISSED** [review]

**Comment by johnoliver** [comment]
@brunoborges has merge conflicts

**Review by markwallace-microsoft — APPROVED** [review]

**Comment by brunoborges** [comment]
@markwallace-microsoft @johnoliver @milderhc hey folks, this PR is 100% ready to go.

**Review by markwallace-microsoft — APPROVED** [review]

**Review by johnoliver — APPROVED** [review]

**Review by markwallace-microsoft — APPROVED** [review]

**Pull request merged**
