### PR TITLE
Python: Added metadata specifying connection stems from MSK code

### PR DESCRIPTION
**Pull request by Jibola**
### Description

* MongoDB drivers are used in various flavors and languages. Making sure we exercise our due diligence in identifying the "origin" of the library calls makes it best to understand how our Atlas servers get accessed. 
* Additionally, bumped the motor version to 3.3.2 to support the DriverInfo tracking behavior.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Review by eavanvalkenburg — APPROVED** [review]
Thanks for adding this!

**Comment by moonbox3** [comment]
Could you please pull the latest code from main and fix the poetry lock/toml conflicts? Thanks!

**Comment by Jibola** [comment]
> Could you please pull the latest code from main and fix the poetry lock/toml conflicts? Thanks!

@moonbox3 addressed the merge conflicts! Would love to get this through the pipe.

**Review by eavanvalkenburg — APPROVED** [review]

**Comment by moonbox3** [comment]
> > Could you please pull the latest code from main and fix the poetry lock/toml conflicts? Thanks!
> 
> @moonbox3 addressed the merge conflicts! Would love to get this through the pipe.

@Jibola looks like you need a quick `ruff . --fix` in the python directory, and it'll fix that last issue. Once that is done, I will approve and move it through.

**Review by moonbox3 — APPROVED** [review]

**Pull request merged**
