### PR TITLE
Bring embeddings and memory to KernelHttpServer

### PR DESCRIPTION
**Pull request by craigomatic**
### Motivation and Context
This change modifies the expected headers at the KernelHttpServer and allows future samples to leverage memory/embedding capabilities via the KernelHttpServer.

### Description
* Introduces distinct headers for completion and embedding 
  * Allows one to have completion endpoint on Azure OpenAI and embedding endpoint on OpenAI, for example
* Updates dependent app samples to use the new header convention 

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by dluc** [comment]
Could you expand on the motivation/context pls? From an end user perspective, or from a dev perspective, why is this change needed? I'm a bit confused about the idea of exposing "embeddings" to the frontend app, e.g. I wouldn't expect an app to deal with vectors, or why does it need to?

**Comment by dluc** [comment]
LGTM, waiting for someone to test the apps and sign off

**Review by awharrison-28 — APPROVED** [review]
All 3 samples tested locally by @glahaye

**Review by shawncal — APPROVED** [review]

**Review by glahaye — APPROVED** [review]
LGTM

**Pull request merged**
