### PR TITLE
Fix potential github action smells

### PR DESCRIPTION
**Pull request by ceddy4395**
### Description
Hey! 🙂
I want to contribute the following changes to your workflow:

- Use commit hash instead of tags for action versions
- Use fixed version for runs-on argument
- Avoid jobs without timeouts
- Prevent running issue/PR actions on forks
- Steps should only perform a single command
- Use names for run steps

These changes are part of a research Study at TU Delft looking at GitHub Action Smells. [Find out more](https://ceddy4395.github.io/research/gha-smells.html)

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by ceddy4395** [comment]
@microsoft-github-policy-service agree

**Review by RogerBarreto — CHANGES_REQUESTED** [review]
Can you point a reference why using the SHA instead of Major version is a smell?

Actually not being specific gives us the flexibility to be updated from patches and bugs found during a major version.

Similar questions were raised in this Repo with no detail.

https://github.com/dbeaver/dbeaver/pull/29273

**Comment by ceddy4395** [comment]
@RogerBarreto [Here is a scientific paper](https://www.usenix.org/conference/usenixsecurity22/presentation/koishybayev) and [a blog post](https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash) about potential security risks related to GitHub Actions

**Comment by matthewbolanos** [comment]
Going to close this out because the team has decided that we'll remove both of these actions.

**Pull request closed without merging**
