### PR TITLE
Java: Complete porting TextSkill

### PR DESCRIPTION
**Pull request by johnoliver**
Additionally removes the defaulting of the name for an annotated native input parameter and requires explicit naming of the input name

### CODE REVIEW

**Comment by 1983Thai** [comment]
b4d555d6552076a7f581481a1905578e989bffa5

**Review by 1983Thai — APPROVED** [review]
9faa7e935007d8628035c95f009d51ee35b13ab2

**Review by 1983Thai — APPROVED** [review]
9faa7e935007d8628035c95f009d51ee35b13ab2

**Comment by 1983Thai** [comment]
9faa7e935007d8628035c95f009d51ee35b13ab2

**Review by 1983Thai — APPROVED** [review]
java/semantickernel-api/src/main/java/com/microsoft/semantickernel/skilldefinition/annotations/SKFunctionParameters.java

**Review by markwallace-microsoft — APPROVED** [review]

**Review by markwallace-microsoft — APPROVED** [review]

**Review by markwallace-microsoft — APPROVED** [review]

**Pull request merged**
