### PR TITLE
Fix Example14_Memory.cs example strings

### PR DESCRIPTION
**Pull request by alexchaomander**
### Motivation and Context
Error in documentation for the API Azure Function. 

### Description
This PR fixes the paths in the different places in the codebase that had the incorrect path. 

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [ ] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by craigomatic** [comment]
Some of this was taken care of in #25, we should sync these PRs as 25 also renames the Azure Function to make it less confusing vs. Semantic Kernel's view of what a function is.

**Comment by alexchaomander** [comment]
@craigomatic do you want to just incorporate the extra changes into yours then? Then we can just close this PR. 

I think it would be changing `samples/dotnet/kernel-syntax-examples/Example14_Memory.cs` and `samples/notebooks/dotnet/6-memory-and-embeddings.ipynb` to match what you're renaming the Azure Function

**Comment by dluc** [comment]
@craigomatic could you help understanding in which order to merge this and #25 ?

**Comment by dluc** [comment]
FYI #25 merged

**Comment by alexchaomander** [comment]
@craigomatic @dluc updated!

**Review by shawncal — APPROVED** [review]

**Pull request merged**
