### PR TITLE
.Net: Update FlowOrchestrator to use yaml plugins and reliability improvement

### PR DESCRIPTION
**Pull request by yan-li**
### Motivation and Context

1. Update FlowOrchestrator to use yaml plugin definitions
2. Necessary changes to allow non-chat AI Service for ReAct, for better reliability
3. Some bug fix for repeatable steps

### Description
as above

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
@yan-li We have converted all of the kernel syntax samples so they can be run as integration tests. Example74_FlowOrchestrator uses Console.ReadLine which I've been told causes a proble. Could you take a look at this. Thanks!

**Comment by Krzysztof318** [comment]
Problem with flow orchestrator sample is RunInteractiveAsync method. Maybe good way is remove RunInteractiveAsync and leave only RunSampleAsync (with updated console to this)?

**Comment by yan-li** [comment]
> @yan-li We have converted all of the kernel syntax samples so they can be run as integration tests. Example74_FlowOrchestrator uses Console.ReadLine which I've been told causes a proble. Could you take a look at this. Thanks!

updated to use `ILogger` and `WriteLine` from `BaseTest`

**Comment by yan-li** [comment]
> Problem with flow orchestrator sample is RunInteractiveAsync method. Maybe good way is remove RunInteractiveAsync and leave only RunSampleAsync (with updated console to this)?

updated.

**Review by markwallace-microsoft — APPROVED** [review]

**Review by dmytrostruk — APPROVED** [review]

**Review by dmytrostruk — APPROVED** [review]

**Pull request merged**
