### PR TITLE
.Net: Demos: add folder for  F# script samples .fsx and one with hugging face 🤗 chat completion

### PR DESCRIPTION
**Pull request by jkone27**
### Motivation and Context

image

### Description

add a folder for F# script demos, to allow people to add more single files samples for .fsx files, which can load nuget packages and are a nice strongly typed alternative to python, a great feat of F# in the dotnet ecosystem. 
similarly cs scripts can also be created but require global tools, F# naturally excels in scripting 

to run a script one can use VsCode + Ionide + dotnet-sdk or VS or Rider, or even run the script from commandline `dotnet fsi script.fsx`

### Contribution Checklist

- [ X] The code builds clean without any errors or warnings
- [ X] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ X] All unit tests pass, and I have added new tests where possible
- [ X] I didn't break anyone :smile:

### CODE REVIEW

**Comment by jkone27** [comment]
@microsoft-github-policy-service agree

**Review by westey-m — APPROVED** [review]

**Comment by jkone27** [comment]
hello, any feedback from the team? cheers

**Comment by jkone27** [comment]
@westey-m can this be merged? i dont think it impacts other checks, i can keep it up to date but i think it can also be done by mantainers just with update branch since is just doc will alwasy work..

**Comment by westey-m** [comment]
@jkone27, thanks for the contribution, the pr just needs another review from another team member.  I'll try and get someone to take a look.

**Review by markwallace-microsoft — APPROVED** [review]

**Comment by markwallace-microsoft** [comment]
Hi @jkone27 I'm going to merge this today. Hopefully there will be some interest and we'll get more samples. Thanks for the contribution.

**Comment by jkone27** [comment]
thanks, also really nice demos yesteday at .NET conf focus on AI : )

**Pull request merged**
