### PR TITLE
Python: add missing init from prompt_template folder

### LINKED ISSUE #5172: Python: `ModuleNotFoundError: No module named 'semantic_kernel.prompt_template'`
**Describe the bug**
`from semantic_kernel.prompt_template.input_variable import InputVariable` fails with the exception `ModuleNotFoundError: No module named 'semantic_kernel.prompt_template'`

This most probably happens because of missing '__init__.py' in `https://github.com/microsoft/semantic-kernel/tree/main/python/semantic_kernel/prompt_template`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

### PR DESCRIPTION
**Pull request by eavanvalkenburg**
### Motivation and Context

adds a __init__ file to the prompt_template folder which exposes the most important classes from the files.

fixes #5172 

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/2ff1c827ce393a6c52f946eb0a1ce85339d08b69/README.md">Py3.10 Test Coverage</a><details><summary>Python 3.10 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>4994</b></td><td><b>937</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.10 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1042 | 1 :zzz: | 0 :x: | 0 :fire: | 20.586s :stopwatch: |

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/2ff1c827ce393a6c52f946eb0a1ce85339d08b69/README.md">Py3.11 Test Coverage</a><details><summary>Python 3.11 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>4994</b></td><td><b>937</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.11 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1042 | 1 :zzz: | 0 :x: | 0 :fire: | 18.622s :stopwatch: |

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/2ff1c827ce393a6c52f946eb0a1ce85339d08b69/README.md">Py3.9 Test Coverage</a><details><summary>Python 3.9 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>4988</b></td><td><b>939</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.9 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1042 | 2 :zzz: | 0 :x: | 0 :fire: | 17.170s :stopwatch: |

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/2ff1c827ce393a6c52f946eb0a1ce85339d08b69/README.md">Py3.8 Test Coverage</a><details><summary>Python 3.8 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td><b>TOTAL</b></td><td><b>4851</b></td><td><b>945</b></td><td><b>81%</b></td><td>&nbsp;</td></tr></tbody></table><i>report-only-changed-files is enabled. No files were changed during this commit :)</i></details>

## Python 3.8 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1042 | 11 :zzz: | 0 :x: | 0 :fire: | 18.881s :stopwatch: |

**Review by moonbox3 — APPROVED** [review]

**Review by juliomenendez — APPROVED** [review]

**Pull request merged**
