### PR TITLE
.Net: Move Gemini models to InternalModels directory

### LINKED ISSUE #5676: .Net Connectors - Models Folder
### Models Dedicated Folder for internal (Request/Response) related models within the connectors.

### PR DESCRIPTION
**Pull request by Krzysztof318**
### Motivation and Context

Resolve #5676

### Description

The Gemini internal related classes that were directly located under the Gemini directory have been moved to a new subdirectory named InternalModels. This change is made to better organize the project structure, keeping internal models separate for improved code maintainability.

cc: @RogerBarreto 

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Review by RogerBarreto — APPROVED** [review]

**Comment by RogerBarreto** [comment]
Suggest using `Models` as the folder name

**Comment by Krzysztof318** [comment]
@RogerBarreto I was thinking about just "Models" but I am not sure it conveys meaning internal models. Because in Core we have public models and in InternalModels we have only internals. But if you think it doesn't matter so much I can change folder to "models".

**Comment by RogerBarreto** [comment]
I see, suggestion:

`Google/Core/Models/Gemini` internal

`Google/Models/Gemini` public

This also opens another point, where public `models` should not necessarily be in the `Core`...

**Comment by Krzysztof318** [comment]
@RogerBarreto done
image

**Review by markwallace-microsoft — APPROVED** [review]

**Pull request merged**
