### PR TITLE
Adding azure AD B2C to the copilot sample app

### PR DESCRIPTION
**Pull request by wayne-o**
### Motivation and Context

Adding AzureADB2C support to the copilot sample app.

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [ ] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by wayne-o** [comment]
> @wayne-o please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="{Made Software Ltd}"]

**Comment by wayne-o** [comment]
Loging in works now but the MS Graph plugin activation needs some work - I'll try and get that done tonight

**Comment by wayne-o** [comment]
I think it will need to use https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow for this to work - is that correct? If so then I will start looking into it - otherwise lmk if there's an easier approach :)

**Comment by teresaqhoang** [comment]
> I am not sure this is going to be possible - keep getting invalid audience errors when using the token :/

@wayne-o Looks like there's a [MS Graph application pre-requisite](https://learn.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-get-started?tabs=app-reg-ga#grant-api-access) to enable the MS Graph APIs, did you configure your Azure application with the required permissions? 

This [sample ](https://github.com/Azure-Samples/ms-identity-b2c-javascript-nodejs-management/tree/main/Chapter1) seems like it gives a pretty comprehensive overview of how use MSAL to obtain a JWT token, you can try to compare your work to this to see if there's any gaps. 

Let me know if you're able to get it to a working state and I can help test!

**Comment by teresaqhoang** [comment]
@wayne-o Adding the `PR:paused` label to this PR, please remove the label if you're going to going to resume this PR or close this PR out if you want to abandon this work. 

Feel free to open an issue as a feature request for the team to add Azure AD B2C support!

**Comment by matthewbolanos** [comment]
Closing this PR for now; if you want to pick this back up, feel free to open the PR back up :)

**Pull request closed without merging**
