### PR TITLE
Pinecone memory connector

### PR DESCRIPTION
**Pull request by dmytrostruk**
### Motivation and Context

Pinecone vector database implementation: https://docs.pinecone.io/docs/overview.
Original PR: https://github.com/microsoft/semantic-kernel/pull/770

### Description

Implementation logic and structure is similar to already existing Qdrant connector.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by Kevdome3000** [comment]
@dmytrostruk I believe the Pinecone example from the Kernel-Syntax-Examples wasn't added to the Program.cs file

**Comment by dmytrostruk** [comment]
> @dmytrostruk I believe the Pinecone example from the Kernel-Syntax-Examples wasn't added to the Program.cs file

@shawncal Should we add Pinecone example to KernelSyntaxExamples Program.cs? I think it was added in original PR.

**Comment by shawncal** [comment]
> > @dmytrostruk I believe the Pinecone example from the Kernel-Syntax-Examples wasn't added to the Program.cs file
> 
> @shawncal Should we add Pinecone example to KernelSyntaxExamples Program.cs? I think it was added in original PR.

Yes, absolutely! Must have been a bad merge (that file sees a lot of conflicts, growth).

**Comment by shawncal** [comment]
> > > @dmytrostruk I believe the Pinecone example from the Kernel-Syntax-Examples wasn't added to the Program.cs file
> > 
> > 
> > @shawncal Should we add Pinecone example to KernelSyntaxExamples Program.cs? I think it was added in original PR.
> 
> Yes, absolutely! Must have been a bad merge (that file sees a lot of conflicts, growth).

Added back. Good catch!

**Review by shawncal — APPROVED** [review]

**Pull request merged**
