### PR TITLE
Upgraded Python dependencies in HuggingFace HTTP server sample

### PR DESCRIPTION
**Pull request by dmytrostruk**
### Motivation and Context

Upgraded Python dependencies in HuggingFace HTTP server sample to address security issues.
Verified that HTTP server works as expected after dependencies upgrade.

### Description

1. Upgraded `joblib` to 1.2.0.
2. Upgraded `torch` to 1.13.1.
3. Upgraded `Pillow` to 9.3.0.
4. Upgraded `Werkzeug` to 2.2.3.
5. Upgraded `numpy` to 1.22.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [x] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Review by mkarle — APPROVED** [review]

**Comment by dluc** [comment]
the diff is empty, just me?

**Comment by mkarle** [comment]
Not sure what's wrong with the diff, but I checked out the pr and the dependencies matched the versions in the description.

**Comment by dmytrostruk** [comment]
@dluc @mkarle For some reason, GitHub doesn't catch `requirements.txt` diff, it thinks that it's a binary file. That's why I put list of upgraded dependencies and their versions in PR description.

**Comment by shawncal** [comment]
Updated the requirements.txt to UTF-8, which git suddenly understood to be non-binary. Dependabot then picked up and resolved all the vulnerabilities. Closing this one, as I fear it might convert requirements.txt back to its original UTF-16 encoding.

**Pull request closed without merging**
