### PR TITLE
Python: Issue-2372: A sample implementation(NL-to-SQL case) of the evaluation framework

### PR DESCRIPTION
**Pull request by caramelmacch**
### Motivation and Context

Please help reviewers and future users, providing the following information:
  1. Why is this change required?
  
  **FMOps**(Fundamental Model Ops) is a critical aspect of the lifecycle management of the performance and quality of Open AI based systems. It consists of several steps to ensure effective system operation and improvement.  **The evaluation framework** plays an important role in the experimentation phase, facilitating rapid experimentation and providing valuable insights. 
image
  3. What problem does it solve?
  
This sample is a reference implementation of the evaluation framework to evaluate the quality and the performance of NL-to-SQL capability of Azure Open AI service.

This is the sample result reports.
image

  5. What scenario does it contribute to?

This helps people to understand how to evaluate the performance of LLM based systems. It also provides how to create plugins with native functions.

  7. If it fixes an open issue, please link to the issue here.

https://github.com/microsoft/semantic-kernel/issues/2372

### Description

It is basically a Jupyter notebook that shows how to evaluate generated completions from Azure Open AI service. It consists of three steps like loading evaluation dataset, assessing metrics and generating report. The result provides multiple statistical metrics and evaluation techniques to assess the performance of Azure Open AI models in NL-to-SQL tasks. The metrics contains query exact match, semantic accuracy(=result exact match), query syntax validity, query diff, Levenshtein score, and cosine similarity, which provide valuable insights into the performance and accuracy of the NL-to-SQL system.

The evaluation framework connects directly to Azure OpenAI service for generating SQL from NL(Natural Language) input and calculating Cosine Similarity, so you need to create your own Azure OpenAI instance with both GPT model for NL-to-SQL tasks and Text Embedding model(like text-embedding-ada-002) for getting embedding vectors.

The framework also uses Azure SQL Server to check SQL Validiy, Results and Execution Time, so you need to create your own Azure SQL Server instance. It uses a sample database called "AdventureWorksLT" for evaluation, so you need to create it in your Azure SQL Server instance. 

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by caramelmacch** [comment]
@shawncal @nacharya1 H all, I know you guys are all busy. thanks for managing SK.
It's been for a while since I created this PR. Is there any issue or I just need to wait more for your review and merging? Thanks in advance!

**Comment by nacharya1** [comment]
@shawncal can you take a look into this?

**Comment by moonbox3** [comment]
Thanks for your contribution. We're going to close this PR as this should be supported by AzureOpenAI studio.

**Comment by caramelmacch** [comment]
@moonbox3, what do you mean being supported by AzureOpenAI studio? I need to move this sample to somewhere else? Just give me some advices on it. thanks in advance!

**Comment by moonbox3** [comment]
@caramelmacch, per our product team, this functionality should be supported by AzureOpenAI studio and not Semantic Kernel. No action on your part, unless you want to follow up with AzureOpenAI studio about their status/plans to support the functionality.

**Pull request closed without merging**
