### PR TITLE
Wrong reference path to "add_text_completion_service" function

### PR DESCRIPTION
**Pull request by LazaUK**
Right now demo code fails on attempt to execute "kernel.add_text_completion_service", as Kernel class doesn't have "add_text_completion_service" function. Correct reference path should be "kernel.config.add_text_completion_service"

### Motivation and Context

1. Wrong reference within the demo code
2. Fixing issue with AttributeError: 'Kernel' object has no attribute 'add_text_completion_service'
3. Use of provided GettingStarting demo code
4. https://github.com/microsoft/semantic-kernel/issues/854

### Description

Problem arise on attempts to execute first Python SK code on the Getting Started, as there is a wrong reference to the Python function.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [ ] The PR follows SK Contribution Guidelines (https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
- [ ] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`
- [ ] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Comment by LazaUK** [comment]
Updated issue # 854, to advise others before this PR is merged.

**Comment by shawncal** [comment]
Thanks for the contribution. The README matches the code in the repo (config was recently removed), but is just out of sync with the pip package. New pip packages coming out today! Check back soon.

Closing as duplicate of https://github.com/microsoft/semantic-kernel/pull/834

**Comment by shawncal** [comment]
New pip packages released:
https://pypi.org/project/semantic-kernel/0.2.7.dev0/

Closing as the pip packages now match the documentation. Thanks again for raising this!

**Comment by LazaUK** [comment]
Ok, thanks for the clarification!

**Comment by rakeshmothukuru1** [comment]
Issue still exists

**Pull request closed without merging**
