### PR TITLE
add verify settings to gitattributes and editorconfig

### PR DESCRIPTION
**Pull request by SimonCropp**
https://github.com/VerifyTests/Verify?tab=readme-ov-file#editorconfig-settings

### CODE REVIEW

**Review by dmytrostruk — COMMENTED** [review]
@SimonCropp Thanks for your contribution! Could you please provide a little bit more context in PR description why this change is required? Thanks a lot!

**Comment by SimonCropp** [comment]
@dmytrostruk https://github.com/VerifyTests/Verify?tab=readme-ov-file#editorconfig-settings

**Review by RogerBarreto — APPROVED** [review]

**Comment by SimonCropp** [comment]
bump

**Comment by moonbox3** [comment]
Hi @dmytrostruk: is this something we still want to move forward with? Looking to clean up some older PRs. Thanks.

**Comment by dmytrostruk** [comment]
> Hi @dmytrostruk: is this something we still want to move forward with? Looking to clean up some older PRs. Thanks.

Taking into account that `Verify` library is used only in one unit test in entire codebase, I created another PR to remove this dependency: https://github.com/microsoft/semantic-kernel/pull/9879. Based on that, I think we can close this PR.

@SimonCropp In all cases, thanks for your contribution and your interest in Semantic Kernel!

**Pull request closed without merging**
